// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "matrix_mult.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic matrix_mult::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic matrix_mult::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<16> matrix_mult::ap_ST_fsm_state1 = "1";
const sc_lv<16> matrix_mult::ap_ST_fsm_state2 = "10";
const sc_lv<16> matrix_mult::ap_ST_fsm_state3 = "100";
const sc_lv<16> matrix_mult::ap_ST_fsm_state4 = "1000";
const sc_lv<16> matrix_mult::ap_ST_fsm_state5 = "10000";
const sc_lv<16> matrix_mult::ap_ST_fsm_state6 = "100000";
const sc_lv<16> matrix_mult::ap_ST_fsm_state7 = "1000000";
const sc_lv<16> matrix_mult::ap_ST_fsm_state8 = "10000000";
const sc_lv<16> matrix_mult::ap_ST_fsm_state9 = "100000000";
const sc_lv<16> matrix_mult::ap_ST_fsm_state10 = "1000000000";
const sc_lv<16> matrix_mult::ap_ST_fsm_state11 = "10000000000";
const sc_lv<16> matrix_mult::ap_ST_fsm_state12 = "100000000000";
const sc_lv<16> matrix_mult::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<16> matrix_mult::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<16> matrix_mult::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<16> matrix_mult::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<32> matrix_mult::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> matrix_mult::ap_const_lv32_1 = "1";
const sc_lv<1> matrix_mult::ap_const_lv1_0 = "0";
const sc_lv<32> matrix_mult::ap_const_lv32_2 = "10";
const sc_lv<32> matrix_mult::ap_const_lv32_4 = "100";
const sc_lv<32> matrix_mult::ap_const_lv32_5 = "101";
const sc_lv<32> matrix_mult::ap_const_lv32_7 = "111";
const sc_lv<32> matrix_mult::ap_const_lv32_8 = "1000";
const sc_lv<32> matrix_mult::ap_const_lv32_9 = "1001";
const sc_lv<32> matrix_mult::ap_const_lv32_A = "1010";
const sc_lv<32> matrix_mult::ap_const_lv32_B = "1011";
const sc_lv<32> matrix_mult::ap_const_lv32_C = "1100";
const sc_lv<32> matrix_mult::ap_const_lv32_D = "1101";
const sc_lv<32> matrix_mult::ap_const_lv32_E = "1110";
const sc_lv<5> matrix_mult::ap_const_lv5_0 = "00000";
const sc_lv<1> matrix_mult::ap_const_lv1_1 = "1";
const sc_lv<32> matrix_mult::ap_const_lv32_3 = "11";
const sc_lv<32> matrix_mult::ap_const_lv32_6 = "110";
const sc_lv<32> matrix_mult::ap_const_lv32_F = "1111";
const sc_lv<5> matrix_mult::ap_const_lv5_14 = "10100";
const sc_lv<5> matrix_mult::ap_const_lv5_1 = "1";
const sc_lv<4> matrix_mult::ap_const_lv4_0 = "0000";
const sc_lv<2> matrix_mult::ap_const_lv2_0 = "00";
const bool matrix_mult::ap_const_boolean_1 = true;

matrix_mult::matrix_mult(sc_module_name name) : sc_module(name), mVcdFile(0) {
    a_buff_U = new matrix_mult_a_buff("a_buff_U");
    a_buff_U->clk(ap_clk);
    a_buff_U->reset(ap_rst);
    a_buff_U->address0(a_buff_address0);
    a_buff_U->ce0(a_buff_ce0);
    a_buff_U->we0(a_buff_we0);
    a_buff_U->d0(a_q0);
    a_buff_U->q0(a_buff_q0);
    b_buff_U = new matrix_mult_a_buff("b_buff_U");
    b_buff_U->clk(ap_clk);
    b_buff_U->reset(ap_rst);
    b_buff_U->address0(b_buff_address0);
    b_buff_U->ce0(b_buff_ce0);
    b_buff_U->we0(b_buff_we0);
    b_buff_U->d0(b_q0);
    b_buff_U->q0(b_buff_q0);
    c_buff_U = new matrix_mult_a_buff("c_buff_U");
    c_buff_U->clk(ap_clk);
    c_buff_U->reset(ap_rst);
    c_buff_U->address0(c_buff_address0);
    c_buff_U->ce0(c_buff_ce0);
    c_buff_U->we0(c_buff_we0);
    c_buff_U->d0(accum_0_reg_212);
    c_buff_U->q0(c_buff_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_a_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( zext_ln18_1_fu_330_p1 );

    SC_METHOD(thread_a_buff_address0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( zext_ln18_5_fu_344_p1 );
    sensitive << ( zext_ln33_3_fu_527_p1 );

    SC_METHOD(thread_a_buff_ce0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_a_buff_we0);
    sensitive << ( ap_CS_fsm_state4 );

    SC_METHOD(thread_a_ce0);
    sensitive << ( ap_CS_fsm_state3 );

    SC_METHOD(thread_accum_fu_576_p2);
    sensitive << ( mul_ln33_reg_813 );
    sensitive << ( accum_0_reg_212 );

    SC_METHOD(thread_add_ln18_1_fu_316_p2);
    sensitive << ( shl_ln18_1_reg_684 );
    sensitive << ( zext_ln17_fu_300_p1 );

    SC_METHOD(thread_add_ln18_2_fu_294_p2);
    sensitive << ( zext_ln18_2_fu_290_p1 );
    sensitive << ( zext_ln18_fu_286_p1 );

    SC_METHOD(thread_add_ln18_3_fu_339_p2);
    sensitive << ( add_ln18_2_reg_689 );
    sensitive << ( zext_ln18_4_fu_335_p1 );

    SC_METHOD(thread_add_ln18_fu_325_p2);
    sensitive << ( shl_ln_reg_679 );
    sensitive << ( zext_ln18_3_fu_321_p1 );

    SC_METHOD(thread_add_ln24_1_fu_406_p2);
    sensitive << ( shl_ln24_1_reg_725 );
    sensitive << ( zext_ln23_fu_390_p1 );

    SC_METHOD(thread_add_ln24_2_fu_384_p2);
    sensitive << ( zext_ln24_2_fu_380_p1 );
    sensitive << ( zext_ln24_fu_376_p1 );

    SC_METHOD(thread_add_ln24_3_fu_429_p2);
    sensitive << ( add_ln24_2_reg_730 );
    sensitive << ( zext_ln24_4_fu_425_p1 );

    SC_METHOD(thread_add_ln24_fu_415_p2);
    sensitive << ( shl_ln1_reg_720 );
    sensitive << ( zext_ln24_3_fu_411_p1 );

    SC_METHOD(thread_add_ln33_1_fu_522_p2);
    sensitive << ( add_ln33_reg_761 );
    sensitive << ( zext_ln33_2_fu_518_p1 );

    SC_METHOD(thread_add_ln33_2_fu_556_p2);
    sensitive << ( zext_ln33_5_fu_552_p1 );
    sensitive << ( zext_ln33_4_fu_540_p1 );

    SC_METHOD(thread_add_ln33_3_fu_562_p2);
    sensitive << ( zext_ln35_reg_775 );
    sensitive << ( add_ln33_2_fu_556_p2 );

    SC_METHOD(thread_add_ln33_fu_474_p2);
    sensitive << ( zext_ln33_1_fu_470_p1 );
    sensitive << ( zext_ln33_fu_458_p1 );

    SC_METHOD(thread_add_ln35_fu_496_p2);
    sensitive << ( add_ln33_reg_761 );
    sensitive << ( zext_ln35_fu_492_p1 );

    SC_METHOD(thread_add_ln42_1_fu_653_p2);
    sensitive << ( tmp_7_reg_836 );
    sensitive << ( zext_ln41_fu_623_p1 );

    SC_METHOD(thread_add_ln42_2_fu_617_p2);
    sensitive << ( zext_ln42_1_fu_613_p1 );
    sensitive << ( zext_ln42_fu_601_p1 );

    SC_METHOD(thread_add_ln42_3_fu_643_p2);
    sensitive << ( add_ln42_2_reg_841 );
    sensitive << ( zext_ln42_4_fu_639_p1 );

    SC_METHOD(thread_add_ln42_fu_662_p2);
    sensitive << ( tmp_6_reg_831 );
    sensitive << ( zext_ln42_3_fu_658_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( icmp_ln40_fu_581_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( icmp_ln40_fu_581_p2 );

    SC_METHOD(thread_b_address0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( zext_ln24_1_fu_420_p1 );

    SC_METHOD(thread_b_buff_address0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( zext_ln24_5_fu_434_p1 );
    sensitive << ( zext_ln33_6_fu_567_p1 );

    SC_METHOD(thread_b_buff_ce0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_b_buff_we0);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_b_ce0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_c_address0);
    sensitive << ( ap_CS_fsm_state16 );
    sensitive << ( zext_ln42_2_fu_667_p1 );

    SC_METHOD(thread_c_buff_address0);
    sensitive << ( c_buff_addr_1_reg_780 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( zext_ln42_5_fu_648_p1 );

    SC_METHOD(thread_c_buff_ce0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state15 );

    SC_METHOD(thread_c_buff_we0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( icmp_ln32_fu_506_p2 );

    SC_METHOD(thread_c_ce0);
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_c_d0);
    sensitive << ( c_buff_q0 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_c_we0);
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_i_1_fu_354_p2);
    sensitive << ( i1_0_reg_168 );

    SC_METHOD(thread_i_2_fu_587_p2);
    sensitive << ( i3_0_reg_236 );

    SC_METHOD(thread_i_fu_264_p2);
    sensitive << ( i_0_reg_146 );

    SC_METHOD(thread_icmp_ln16_fu_258_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_146 );

    SC_METHOD(thread_icmp_ln17_fu_304_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( j_0_reg_157 );

    SC_METHOD(thread_icmp_ln22_fu_348_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( i1_0_reg_168 );

    SC_METHOD(thread_icmp_ln23_fu_394_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( j2_0_reg_179 );

    SC_METHOD(thread_icmp_ln29_fu_438_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( m_0_reg_190 );

    SC_METHOD(thread_icmp_ln30_fu_480_p2);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( o_0_reg_201 );

    SC_METHOD(thread_icmp_ln32_fu_506_p2);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( n_0_reg_225 );

    SC_METHOD(thread_icmp_ln40_fu_581_p2);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( i3_0_reg_236 );

    SC_METHOD(thread_icmp_ln41_fu_627_p2);
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( j4_0_reg_247 );

    SC_METHOD(thread_j_1_fu_400_p2);
    sensitive << ( j2_0_reg_179 );

    SC_METHOD(thread_j_2_fu_633_p2);
    sensitive << ( j4_0_reg_247 );

    SC_METHOD(thread_j_fu_310_p2);
    sensitive << ( j_0_reg_157 );

    SC_METHOD(thread_m_fu_444_p2);
    sensitive << ( m_0_reg_190 );

    SC_METHOD(thread_mul_ln33_fu_572_p2);
    sensitive << ( a_buff_load_reg_803 );
    sensitive << ( b_buff_load_reg_808 );

    SC_METHOD(thread_n_fu_512_p2);
    sensitive << ( n_0_reg_225 );

    SC_METHOD(thread_o_fu_486_p2);
    sensitive << ( o_0_reg_201 );

    SC_METHOD(thread_shl_ln18_1_fu_278_p3);
    sensitive << ( i_0_reg_146 );

    SC_METHOD(thread_shl_ln1_fu_360_p3);
    sensitive << ( i1_0_reg_168 );

    SC_METHOD(thread_shl_ln24_1_fu_368_p3);
    sensitive << ( i1_0_reg_168 );

    SC_METHOD(thread_shl_ln_fu_270_p3);
    sensitive << ( i_0_reg_146 );

    SC_METHOD(thread_tmp_4_fu_450_p3);
    sensitive << ( m_0_reg_190 );

    SC_METHOD(thread_tmp_5_fu_462_p3);
    sensitive << ( m_0_reg_190 );

    SC_METHOD(thread_tmp_6_fu_593_p3);
    sensitive << ( i3_0_reg_236 );

    SC_METHOD(thread_tmp_7_fu_605_p3);
    sensitive << ( i3_0_reg_236 );

    SC_METHOD(thread_tmp_8_fu_532_p3);
    sensitive << ( n_0_reg_225 );

    SC_METHOD(thread_tmp_9_fu_544_p3);
    sensitive << ( n_0_reg_225 );

    SC_METHOD(thread_zext_ln17_fu_300_p1);
    sensitive << ( j_0_reg_157 );

    SC_METHOD(thread_zext_ln18_1_fu_330_p1);
    sensitive << ( add_ln18_fu_325_p2 );

    SC_METHOD(thread_zext_ln18_2_fu_290_p1);
    sensitive << ( shl_ln18_1_fu_278_p3 );

    SC_METHOD(thread_zext_ln18_3_fu_321_p1);
    sensitive << ( add_ln18_1_fu_316_p2 );

    SC_METHOD(thread_zext_ln18_4_fu_335_p1);
    sensitive << ( j_0_reg_157 );

    SC_METHOD(thread_zext_ln18_5_fu_344_p1);
    sensitive << ( add_ln18_3_reg_707 );

    SC_METHOD(thread_zext_ln18_fu_286_p1);
    sensitive << ( shl_ln_fu_270_p3 );

    SC_METHOD(thread_zext_ln23_fu_390_p1);
    sensitive << ( j2_0_reg_179 );

    SC_METHOD(thread_zext_ln24_1_fu_420_p1);
    sensitive << ( add_ln24_fu_415_p2 );

    SC_METHOD(thread_zext_ln24_2_fu_380_p1);
    sensitive << ( shl_ln24_1_fu_368_p3 );

    SC_METHOD(thread_zext_ln24_3_fu_411_p1);
    sensitive << ( add_ln24_1_fu_406_p2 );

    SC_METHOD(thread_zext_ln24_4_fu_425_p1);
    sensitive << ( j2_0_reg_179 );

    SC_METHOD(thread_zext_ln24_5_fu_434_p1);
    sensitive << ( add_ln24_3_reg_748 );

    SC_METHOD(thread_zext_ln24_fu_376_p1);
    sensitive << ( shl_ln1_fu_360_p3 );

    SC_METHOD(thread_zext_ln33_1_fu_470_p1);
    sensitive << ( tmp_5_fu_462_p3 );

    SC_METHOD(thread_zext_ln33_2_fu_518_p1);
    sensitive << ( n_0_reg_225 );

    SC_METHOD(thread_zext_ln33_3_fu_527_p1);
    sensitive << ( add_ln33_1_fu_522_p2 );

    SC_METHOD(thread_zext_ln33_4_fu_540_p1);
    sensitive << ( tmp_8_fu_532_p3 );

    SC_METHOD(thread_zext_ln33_5_fu_552_p1);
    sensitive << ( tmp_9_fu_544_p3 );

    SC_METHOD(thread_zext_ln33_6_fu_567_p1);
    sensitive << ( add_ln33_3_fu_562_p2 );

    SC_METHOD(thread_zext_ln33_fu_458_p1);
    sensitive << ( tmp_4_fu_450_p3 );

    SC_METHOD(thread_zext_ln35_1_fu_501_p1);
    sensitive << ( add_ln35_fu_496_p2 );

    SC_METHOD(thread_zext_ln35_fu_492_p1);
    sensitive << ( o_0_reg_201 );

    SC_METHOD(thread_zext_ln41_fu_623_p1);
    sensitive << ( j4_0_reg_247 );

    SC_METHOD(thread_zext_ln42_1_fu_613_p1);
    sensitive << ( tmp_7_fu_605_p3 );

    SC_METHOD(thread_zext_ln42_2_fu_667_p1);
    sensitive << ( add_ln42_reg_859 );

    SC_METHOD(thread_zext_ln42_3_fu_658_p1);
    sensitive << ( add_ln42_1_fu_653_p2 );

    SC_METHOD(thread_zext_ln42_4_fu_639_p1);
    sensitive << ( j4_0_reg_247 );

    SC_METHOD(thread_zext_ln42_5_fu_648_p1);
    sensitive << ( add_ln42_3_fu_643_p2 );

    SC_METHOD(thread_zext_ln42_fu_601_p1);
    sensitive << ( tmp_6_fu_593_p3 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln16_fu_258_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( icmp_ln17_fu_304_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( icmp_ln22_fu_348_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( icmp_ln23_fu_394_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( icmp_ln29_fu_438_p2 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( icmp_ln30_fu_480_p2 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( icmp_ln32_fu_506_p2 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( icmp_ln40_fu_581_p2 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( icmp_ln41_fu_627_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "0000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "matrix_mult_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, a_address0, "(port)a_address0");
    sc_trace(mVcdFile, a_ce0, "(port)a_ce0");
    sc_trace(mVcdFile, a_q0, "(port)a_q0");
    sc_trace(mVcdFile, b_address0, "(port)b_address0");
    sc_trace(mVcdFile, b_ce0, "(port)b_ce0");
    sc_trace(mVcdFile, b_q0, "(port)b_q0");
    sc_trace(mVcdFile, c_address0, "(port)c_address0");
    sc_trace(mVcdFile, c_ce0, "(port)c_ce0");
    sc_trace(mVcdFile, c_we0, "(port)c_we0");
    sc_trace(mVcdFile, c_d0, "(port)c_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, i_fu_264_p2, "i_fu_264_p2");
    sc_trace(mVcdFile, i_reg_674, "i_reg_674");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, shl_ln_fu_270_p3, "shl_ln_fu_270_p3");
    sc_trace(mVcdFile, shl_ln_reg_679, "shl_ln_reg_679");
    sc_trace(mVcdFile, icmp_ln16_fu_258_p2, "icmp_ln16_fu_258_p2");
    sc_trace(mVcdFile, shl_ln18_1_fu_278_p3, "shl_ln18_1_fu_278_p3");
    sc_trace(mVcdFile, shl_ln18_1_reg_684, "shl_ln18_1_reg_684");
    sc_trace(mVcdFile, add_ln18_2_fu_294_p2, "add_ln18_2_fu_294_p2");
    sc_trace(mVcdFile, add_ln18_2_reg_689, "add_ln18_2_reg_689");
    sc_trace(mVcdFile, j_fu_310_p2, "j_fu_310_p2");
    sc_trace(mVcdFile, j_reg_697, "j_reg_697");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, icmp_ln17_fu_304_p2, "icmp_ln17_fu_304_p2");
    sc_trace(mVcdFile, add_ln18_3_fu_339_p2, "add_ln18_3_fu_339_p2");
    sc_trace(mVcdFile, add_ln18_3_reg_707, "add_ln18_3_reg_707");
    sc_trace(mVcdFile, i_1_fu_354_p2, "i_1_fu_354_p2");
    sc_trace(mVcdFile, i_1_reg_715, "i_1_reg_715");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, shl_ln1_fu_360_p3, "shl_ln1_fu_360_p3");
    sc_trace(mVcdFile, shl_ln1_reg_720, "shl_ln1_reg_720");
    sc_trace(mVcdFile, icmp_ln22_fu_348_p2, "icmp_ln22_fu_348_p2");
    sc_trace(mVcdFile, shl_ln24_1_fu_368_p3, "shl_ln24_1_fu_368_p3");
    sc_trace(mVcdFile, shl_ln24_1_reg_725, "shl_ln24_1_reg_725");
    sc_trace(mVcdFile, add_ln24_2_fu_384_p2, "add_ln24_2_fu_384_p2");
    sc_trace(mVcdFile, add_ln24_2_reg_730, "add_ln24_2_reg_730");
    sc_trace(mVcdFile, j_1_fu_400_p2, "j_1_fu_400_p2");
    sc_trace(mVcdFile, j_1_reg_738, "j_1_reg_738");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, icmp_ln23_fu_394_p2, "icmp_ln23_fu_394_p2");
    sc_trace(mVcdFile, add_ln24_3_fu_429_p2, "add_ln24_3_fu_429_p2");
    sc_trace(mVcdFile, add_ln24_3_reg_748, "add_ln24_3_reg_748");
    sc_trace(mVcdFile, m_fu_444_p2, "m_fu_444_p2");
    sc_trace(mVcdFile, m_reg_756, "m_reg_756");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, add_ln33_fu_474_p2, "add_ln33_fu_474_p2");
    sc_trace(mVcdFile, add_ln33_reg_761, "add_ln33_reg_761");
    sc_trace(mVcdFile, icmp_ln29_fu_438_p2, "icmp_ln29_fu_438_p2");
    sc_trace(mVcdFile, o_fu_486_p2, "o_fu_486_p2");
    sc_trace(mVcdFile, o_reg_770, "o_reg_770");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, zext_ln35_fu_492_p1, "zext_ln35_fu_492_p1");
    sc_trace(mVcdFile, zext_ln35_reg_775, "zext_ln35_reg_775");
    sc_trace(mVcdFile, icmp_ln30_fu_480_p2, "icmp_ln30_fu_480_p2");
    sc_trace(mVcdFile, c_buff_addr_1_reg_780, "c_buff_addr_1_reg_780");
    sc_trace(mVcdFile, n_fu_512_p2, "n_fu_512_p2");
    sc_trace(mVcdFile, n_reg_788, "n_reg_788");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, icmp_ln32_fu_506_p2, "icmp_ln32_fu_506_p2");
    sc_trace(mVcdFile, a_buff_q0, "a_buff_q0");
    sc_trace(mVcdFile, a_buff_load_reg_803, "a_buff_load_reg_803");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, b_buff_q0, "b_buff_q0");
    sc_trace(mVcdFile, b_buff_load_reg_808, "b_buff_load_reg_808");
    sc_trace(mVcdFile, mul_ln33_fu_572_p2, "mul_ln33_fu_572_p2");
    sc_trace(mVcdFile, mul_ln33_reg_813, "mul_ln33_reg_813");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, accum_fu_576_p2, "accum_fu_576_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, i_2_fu_587_p2, "i_2_fu_587_p2");
    sc_trace(mVcdFile, i_2_reg_826, "i_2_reg_826");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, tmp_6_fu_593_p3, "tmp_6_fu_593_p3");
    sc_trace(mVcdFile, tmp_6_reg_831, "tmp_6_reg_831");
    sc_trace(mVcdFile, icmp_ln40_fu_581_p2, "icmp_ln40_fu_581_p2");
    sc_trace(mVcdFile, tmp_7_fu_605_p3, "tmp_7_fu_605_p3");
    sc_trace(mVcdFile, tmp_7_reg_836, "tmp_7_reg_836");
    sc_trace(mVcdFile, add_ln42_2_fu_617_p2, "add_ln42_2_fu_617_p2");
    sc_trace(mVcdFile, add_ln42_2_reg_841, "add_ln42_2_reg_841");
    sc_trace(mVcdFile, j_2_fu_633_p2, "j_2_fu_633_p2");
    sc_trace(mVcdFile, j_2_reg_849, "j_2_reg_849");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, icmp_ln41_fu_627_p2, "icmp_ln41_fu_627_p2");
    sc_trace(mVcdFile, add_ln42_fu_662_p2, "add_ln42_fu_662_p2");
    sc_trace(mVcdFile, add_ln42_reg_859, "add_ln42_reg_859");
    sc_trace(mVcdFile, a_buff_address0, "a_buff_address0");
    sc_trace(mVcdFile, a_buff_ce0, "a_buff_ce0");
    sc_trace(mVcdFile, a_buff_we0, "a_buff_we0");
    sc_trace(mVcdFile, b_buff_address0, "b_buff_address0");
    sc_trace(mVcdFile, b_buff_ce0, "b_buff_ce0");
    sc_trace(mVcdFile, b_buff_we0, "b_buff_we0");
    sc_trace(mVcdFile, c_buff_address0, "c_buff_address0");
    sc_trace(mVcdFile, c_buff_ce0, "c_buff_ce0");
    sc_trace(mVcdFile, c_buff_we0, "c_buff_we0");
    sc_trace(mVcdFile, c_buff_q0, "c_buff_q0");
    sc_trace(mVcdFile, i_0_reg_146, "i_0_reg_146");
    sc_trace(mVcdFile, j_0_reg_157, "j_0_reg_157");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, i1_0_reg_168, "i1_0_reg_168");
    sc_trace(mVcdFile, j2_0_reg_179, "j2_0_reg_179");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, m_0_reg_190, "m_0_reg_190");
    sc_trace(mVcdFile, o_0_reg_201, "o_0_reg_201");
    sc_trace(mVcdFile, accum_0_reg_212, "accum_0_reg_212");
    sc_trace(mVcdFile, n_0_reg_225, "n_0_reg_225");
    sc_trace(mVcdFile, i3_0_reg_236, "i3_0_reg_236");
    sc_trace(mVcdFile, j4_0_reg_247, "j4_0_reg_247");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, zext_ln18_1_fu_330_p1, "zext_ln18_1_fu_330_p1");
    sc_trace(mVcdFile, zext_ln18_5_fu_344_p1, "zext_ln18_5_fu_344_p1");
    sc_trace(mVcdFile, zext_ln24_1_fu_420_p1, "zext_ln24_1_fu_420_p1");
    sc_trace(mVcdFile, zext_ln24_5_fu_434_p1, "zext_ln24_5_fu_434_p1");
    sc_trace(mVcdFile, zext_ln35_1_fu_501_p1, "zext_ln35_1_fu_501_p1");
    sc_trace(mVcdFile, zext_ln33_3_fu_527_p1, "zext_ln33_3_fu_527_p1");
    sc_trace(mVcdFile, zext_ln33_6_fu_567_p1, "zext_ln33_6_fu_567_p1");
    sc_trace(mVcdFile, zext_ln42_5_fu_648_p1, "zext_ln42_5_fu_648_p1");
    sc_trace(mVcdFile, zext_ln42_2_fu_667_p1, "zext_ln42_2_fu_667_p1");
    sc_trace(mVcdFile, zext_ln18_2_fu_290_p1, "zext_ln18_2_fu_290_p1");
    sc_trace(mVcdFile, zext_ln18_fu_286_p1, "zext_ln18_fu_286_p1");
    sc_trace(mVcdFile, zext_ln17_fu_300_p1, "zext_ln17_fu_300_p1");
    sc_trace(mVcdFile, add_ln18_1_fu_316_p2, "add_ln18_1_fu_316_p2");
    sc_trace(mVcdFile, zext_ln18_3_fu_321_p1, "zext_ln18_3_fu_321_p1");
    sc_trace(mVcdFile, add_ln18_fu_325_p2, "add_ln18_fu_325_p2");
    sc_trace(mVcdFile, zext_ln18_4_fu_335_p1, "zext_ln18_4_fu_335_p1");
    sc_trace(mVcdFile, zext_ln24_2_fu_380_p1, "zext_ln24_2_fu_380_p1");
    sc_trace(mVcdFile, zext_ln24_fu_376_p1, "zext_ln24_fu_376_p1");
    sc_trace(mVcdFile, zext_ln23_fu_390_p1, "zext_ln23_fu_390_p1");
    sc_trace(mVcdFile, add_ln24_1_fu_406_p2, "add_ln24_1_fu_406_p2");
    sc_trace(mVcdFile, zext_ln24_3_fu_411_p1, "zext_ln24_3_fu_411_p1");
    sc_trace(mVcdFile, add_ln24_fu_415_p2, "add_ln24_fu_415_p2");
    sc_trace(mVcdFile, zext_ln24_4_fu_425_p1, "zext_ln24_4_fu_425_p1");
    sc_trace(mVcdFile, tmp_4_fu_450_p3, "tmp_4_fu_450_p3");
    sc_trace(mVcdFile, tmp_5_fu_462_p3, "tmp_5_fu_462_p3");
    sc_trace(mVcdFile, zext_ln33_1_fu_470_p1, "zext_ln33_1_fu_470_p1");
    sc_trace(mVcdFile, zext_ln33_fu_458_p1, "zext_ln33_fu_458_p1");
    sc_trace(mVcdFile, add_ln35_fu_496_p2, "add_ln35_fu_496_p2");
    sc_trace(mVcdFile, zext_ln33_2_fu_518_p1, "zext_ln33_2_fu_518_p1");
    sc_trace(mVcdFile, add_ln33_1_fu_522_p2, "add_ln33_1_fu_522_p2");
    sc_trace(mVcdFile, tmp_8_fu_532_p3, "tmp_8_fu_532_p3");
    sc_trace(mVcdFile, tmp_9_fu_544_p3, "tmp_9_fu_544_p3");
    sc_trace(mVcdFile, zext_ln33_5_fu_552_p1, "zext_ln33_5_fu_552_p1");
    sc_trace(mVcdFile, zext_ln33_4_fu_540_p1, "zext_ln33_4_fu_540_p1");
    sc_trace(mVcdFile, add_ln33_2_fu_556_p2, "add_ln33_2_fu_556_p2");
    sc_trace(mVcdFile, add_ln33_3_fu_562_p2, "add_ln33_3_fu_562_p2");
    sc_trace(mVcdFile, zext_ln42_1_fu_613_p1, "zext_ln42_1_fu_613_p1");
    sc_trace(mVcdFile, zext_ln42_fu_601_p1, "zext_ln42_fu_601_p1");
    sc_trace(mVcdFile, zext_ln42_4_fu_639_p1, "zext_ln42_4_fu_639_p1");
    sc_trace(mVcdFile, add_ln42_3_fu_643_p2, "add_ln42_3_fu_643_p2");
    sc_trace(mVcdFile, zext_ln41_fu_623_p1, "zext_ln41_fu_623_p1");
    sc_trace(mVcdFile, add_ln42_1_fu_653_p2, "add_ln42_1_fu_653_p2");
    sc_trace(mVcdFile, zext_ln42_3_fu_658_p1, "zext_ln42_3_fu_658_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("matrix_mult.hdltvin.dat");
    mHdltvoutHandle.open("matrix_mult.hdltvout.dat");
}

matrix_mult::~matrix_mult() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete a_buff_U;
    delete b_buff_U;
    delete c_buff_U;
}

void matrix_mult::thread_ap_clk_no_reset_() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln30_fu_480_p2.read()))) {
        accum_0_reg_212 = ap_const_lv32_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        accum_0_reg_212 = accum_fu_576_p2.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln16_fu_258_p2.read(), ap_const_lv1_1))) {
        i1_0_reg_168 = ap_const_lv5_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(icmp_ln23_fu_394_p2.read(), ap_const_lv1_1))) {
        i1_0_reg_168 = i_1_reg_715.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(icmp_ln29_fu_438_p2.read(), ap_const_lv1_1))) {
        i3_0_reg_236 = ap_const_lv5_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && 
                esl_seteq<1,1,1>(icmp_ln41_fu_627_p2.read(), ap_const_lv1_1))) {
        i3_0_reg_236 = i_2_reg_826.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(icmp_ln17_fu_304_p2.read(), ap_const_lv1_1))) {
        i_0_reg_146 = i_reg_674.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_146 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_348_p2.read()))) {
        j2_0_reg_179 = ap_const_lv5_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        j2_0_reg_179 = j_1_reg_738.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln40_fu_581_p2.read()))) {
        j4_0_reg_247 = ap_const_lv5_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        j4_0_reg_247 = j_2_reg_849.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln16_fu_258_p2.read(), ap_const_lv1_0))) {
        j_0_reg_157 = ap_const_lv5_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        j_0_reg_157 = j_reg_697.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(icmp_ln22_fu_348_p2.read(), ap_const_lv1_1))) {
        m_0_reg_190 = ap_const_lv5_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
                esl_seteq<1,1,1>(icmp_ln30_fu_480_p2.read(), ap_const_lv1_1))) {
        m_0_reg_190 = m_reg_756.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln30_fu_480_p2.read()))) {
        n_0_reg_225 = ap_const_lv5_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        n_0_reg_225 = n_reg_788.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln29_fu_438_p2.read()))) {
        o_0_reg_201 = ap_const_lv5_0;
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
                esl_seteq<1,1,1>(icmp_ln32_fu_506_p2.read(), ap_const_lv1_1))) {
        o_0_reg_201 = o_reg_770.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        a_buff_load_reg_803 = a_buff_q0.read();
        b_buff_load_reg_808 = b_buff_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln16_fu_258_p2.read(), ap_const_lv1_0))) {
        add_ln18_2_reg_689 = add_ln18_2_fu_294_p2.read();
        shl_ln18_1_reg_684 = shl_ln18_1_fu_278_p3.read();
        shl_ln_reg_679 = shl_ln_fu_270_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln17_fu_304_p2.read()))) {
        add_ln18_3_reg_707 = add_ln18_3_fu_339_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln22_fu_348_p2.read()))) {
        add_ln24_2_reg_730 = add_ln24_2_fu_384_p2.read();
        shl_ln1_reg_720 = shl_ln1_fu_360_p3.read();
        shl_ln24_1_reg_725 = shl_ln24_1_fu_368_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln23_fu_394_p2.read()))) {
        add_ln24_3_reg_748 = add_ln24_3_fu_429_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln29_fu_438_p2.read()))) {
        add_ln33_reg_761 = add_ln33_fu_474_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln40_fu_581_p2.read()))) {
        add_ln42_2_reg_841 = add_ln42_2_fu_617_p2.read();
        tmp_6_reg_831 = tmp_6_fu_593_p3.read();
        tmp_7_reg_836 = tmp_7_fu_605_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln41_fu_627_p2.read()))) {
        add_ln42_reg_859 = add_ln42_fu_662_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln30_fu_480_p2.read()))) {
        c_buff_addr_1_reg_780 =  (sc_lv<9>) (zext_ln35_1_fu_501_p1.read());
        zext_ln35_reg_775 = zext_ln35_fu_492_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        i_1_reg_715 = i_1_fu_354_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        i_2_reg_826 = i_2_fu_587_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_reg_674 = i_fu_264_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        j_1_reg_738 = j_1_fu_400_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        j_2_reg_849 = j_2_fu_633_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        j_reg_697 = j_fu_310_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        m_reg_756 = m_fu_444_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        mul_ln33_reg_813 = mul_ln33_fu_572_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        n_reg_788 = n_fu_512_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        o_reg_770 = o_fu_486_p2.read();
    }
}

void matrix_mult::thread_a_address0() {
    a_address0 =  (sc_lv<9>) (zext_ln18_1_fu_330_p1.read());
}

void matrix_mult::thread_a_buff_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        a_buff_address0 =  (sc_lv<9>) (zext_ln33_3_fu_527_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        a_buff_address0 =  (sc_lv<9>) (zext_ln18_5_fu_344_p1.read());
    } else {
        a_buff_address0 = "XXXXXXXXX";
    }
}

void matrix_mult::thread_a_buff_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()))) {
        a_buff_ce0 = ap_const_logic_1;
    } else {
        a_buff_ce0 = ap_const_logic_0;
    }
}

void matrix_mult::thread_a_buff_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        a_buff_we0 = ap_const_logic_1;
    } else {
        a_buff_we0 = ap_const_logic_0;
    }
}

void matrix_mult::thread_a_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        a_ce0 = ap_const_logic_1;
    } else {
        a_ce0 = ap_const_logic_0;
    }
}

void matrix_mult::thread_accum_fu_576_p2() {
    accum_fu_576_p2 = (!accum_0_reg_212.read().is_01() || !mul_ln33_reg_813.read().is_01())? sc_lv<32>(): (sc_biguint<32>(accum_0_reg_212.read()) + sc_biguint<32>(mul_ln33_reg_813.read()));
}

void matrix_mult::thread_add_ln18_1_fu_316_p2() {
    add_ln18_1_fu_316_p2 = (!zext_ln17_fu_300_p1.read().is_01() || !shl_ln18_1_reg_684.read().is_01())? sc_lv<7>(): (sc_biguint<7>(zext_ln17_fu_300_p1.read()) + sc_biguint<7>(shl_ln18_1_reg_684.read()));
}

void matrix_mult::thread_add_ln18_2_fu_294_p2() {
    add_ln18_2_fu_294_p2 = (!zext_ln18_2_fu_290_p1.read().is_01() || !zext_ln18_fu_286_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln18_2_fu_290_p1.read()) + sc_biguint<10>(zext_ln18_fu_286_p1.read()));
}

void matrix_mult::thread_add_ln18_3_fu_339_p2() {
    add_ln18_3_fu_339_p2 = (!add_ln18_2_reg_689.read().is_01() || !zext_ln18_4_fu_335_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(add_ln18_2_reg_689.read()) + sc_biguint<10>(zext_ln18_4_fu_335_p1.read()));
}

void matrix_mult::thread_add_ln18_fu_325_p2() {
    add_ln18_fu_325_p2 = (!shl_ln_reg_679.read().is_01() || !zext_ln18_3_fu_321_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(shl_ln_reg_679.read()) + sc_biguint<9>(zext_ln18_3_fu_321_p1.read()));
}

void matrix_mult::thread_add_ln24_1_fu_406_p2() {
    add_ln24_1_fu_406_p2 = (!zext_ln23_fu_390_p1.read().is_01() || !shl_ln24_1_reg_725.read().is_01())? sc_lv<7>(): (sc_biguint<7>(zext_ln23_fu_390_p1.read()) + sc_biguint<7>(shl_ln24_1_reg_725.read()));
}

void matrix_mult::thread_add_ln24_2_fu_384_p2() {
    add_ln24_2_fu_384_p2 = (!zext_ln24_2_fu_380_p1.read().is_01() || !zext_ln24_fu_376_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln24_2_fu_380_p1.read()) + sc_biguint<10>(zext_ln24_fu_376_p1.read()));
}

void matrix_mult::thread_add_ln24_3_fu_429_p2() {
    add_ln24_3_fu_429_p2 = (!add_ln24_2_reg_730.read().is_01() || !zext_ln24_4_fu_425_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(add_ln24_2_reg_730.read()) + sc_biguint<10>(zext_ln24_4_fu_425_p1.read()));
}

void matrix_mult::thread_add_ln24_fu_415_p2() {
    add_ln24_fu_415_p2 = (!shl_ln1_reg_720.read().is_01() || !zext_ln24_3_fu_411_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(shl_ln1_reg_720.read()) + sc_biguint<9>(zext_ln24_3_fu_411_p1.read()));
}

void matrix_mult::thread_add_ln33_1_fu_522_p2() {
    add_ln33_1_fu_522_p2 = (!add_ln33_reg_761.read().is_01() || !zext_ln33_2_fu_518_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(add_ln33_reg_761.read()) + sc_biguint<10>(zext_ln33_2_fu_518_p1.read()));
}

void matrix_mult::thread_add_ln33_2_fu_556_p2() {
    add_ln33_2_fu_556_p2 = (!zext_ln33_5_fu_552_p1.read().is_01() || !zext_ln33_4_fu_540_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln33_5_fu_552_p1.read()) + sc_biguint<10>(zext_ln33_4_fu_540_p1.read()));
}

void matrix_mult::thread_add_ln33_3_fu_562_p2() {
    add_ln33_3_fu_562_p2 = (!add_ln33_2_fu_556_p2.read().is_01() || !zext_ln35_reg_775.read().is_01())? sc_lv<10>(): (sc_biguint<10>(add_ln33_2_fu_556_p2.read()) + sc_biguint<10>(zext_ln35_reg_775.read()));
}

void matrix_mult::thread_add_ln33_fu_474_p2() {
    add_ln33_fu_474_p2 = (!zext_ln33_1_fu_470_p1.read().is_01() || !zext_ln33_fu_458_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln33_1_fu_470_p1.read()) + sc_biguint<10>(zext_ln33_fu_458_p1.read()));
}

void matrix_mult::thread_add_ln35_fu_496_p2() {
    add_ln35_fu_496_p2 = (!add_ln33_reg_761.read().is_01() || !zext_ln35_fu_492_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(add_ln33_reg_761.read()) + sc_biguint<10>(zext_ln35_fu_492_p1.read()));
}

void matrix_mult::thread_add_ln42_1_fu_653_p2() {
    add_ln42_1_fu_653_p2 = (!zext_ln41_fu_623_p1.read().is_01() || !tmp_7_reg_836.read().is_01())? sc_lv<7>(): (sc_biguint<7>(zext_ln41_fu_623_p1.read()) + sc_biguint<7>(tmp_7_reg_836.read()));
}

void matrix_mult::thread_add_ln42_2_fu_617_p2() {
    add_ln42_2_fu_617_p2 = (!zext_ln42_1_fu_613_p1.read().is_01() || !zext_ln42_fu_601_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(zext_ln42_1_fu_613_p1.read()) + sc_biguint<10>(zext_ln42_fu_601_p1.read()));
}

void matrix_mult::thread_add_ln42_3_fu_643_p2() {
    add_ln42_3_fu_643_p2 = (!add_ln42_2_reg_841.read().is_01() || !zext_ln42_4_fu_639_p1.read().is_01())? sc_lv<10>(): (sc_biguint<10>(add_ln42_2_reg_841.read()) + sc_biguint<10>(zext_ln42_4_fu_639_p1.read()));
}

void matrix_mult::thread_add_ln42_fu_662_p2() {
    add_ln42_fu_662_p2 = (!tmp_6_reg_831.read().is_01() || !zext_ln42_3_fu_658_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp_6_reg_831.read()) + sc_biguint<9>(zext_ln42_3_fu_658_p1.read()));
}

void matrix_mult::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void matrix_mult::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void matrix_mult::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void matrix_mult::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void matrix_mult::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void matrix_mult::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void matrix_mult::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void matrix_mult::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void matrix_mult::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void matrix_mult::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void matrix_mult::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void matrix_mult::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void matrix_mult::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void matrix_mult::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void matrix_mult::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void matrix_mult::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void matrix_mult::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && 
         esl_seteq<1,1,1>(icmp_ln40_fu_581_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void matrix_mult::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void matrix_mult::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && 
         esl_seteq<1,1,1>(icmp_ln40_fu_581_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void matrix_mult::thread_b_address0() {
    b_address0 =  (sc_lv<9>) (zext_ln24_1_fu_420_p1.read());
}

void matrix_mult::thread_b_buff_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        b_buff_address0 =  (sc_lv<9>) (zext_ln33_6_fu_567_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        b_buff_address0 =  (sc_lv<9>) (zext_ln24_5_fu_434_p1.read());
    } else {
        b_buff_address0 = "XXXXXXXXX";
    }
}

void matrix_mult::thread_b_buff_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        b_buff_ce0 = ap_const_logic_1;
    } else {
        b_buff_ce0 = ap_const_logic_0;
    }
}

void matrix_mult::thread_b_buff_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        b_buff_we0 = ap_const_logic_1;
    } else {
        b_buff_we0 = ap_const_logic_0;
    }
}

void matrix_mult::thread_b_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        b_ce0 = ap_const_logic_1;
    } else {
        b_ce0 = ap_const_logic_0;
    }
}

void matrix_mult::thread_c_address0() {
    c_address0 =  (sc_lv<9>) (zext_ln42_2_fu_667_p1.read());
}

void matrix_mult::thread_c_buff_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        c_buff_address0 =  (sc_lv<9>) (zext_ln42_5_fu_648_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        c_buff_address0 = c_buff_addr_1_reg_780.read();
    } else {
        c_buff_address0 = "XXXXXXXXX";
    }
}

void matrix_mult::thread_c_buff_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()))) {
        c_buff_ce0 = ap_const_logic_1;
    } else {
        c_buff_ce0 = ap_const_logic_0;
    }
}

void matrix_mult::thread_c_buff_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && 
         esl_seteq<1,1,1>(icmp_ln32_fu_506_p2.read(), ap_const_lv1_1))) {
        c_buff_we0 = ap_const_logic_1;
    } else {
        c_buff_we0 = ap_const_logic_0;
    }
}

void matrix_mult::thread_c_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        c_ce0 = ap_const_logic_1;
    } else {
        c_ce0 = ap_const_logic_0;
    }
}

void matrix_mult::thread_c_d0() {
    c_d0 = c_buff_q0.read();
}

void matrix_mult::thread_c_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        c_we0 = ap_const_logic_1;
    } else {
        c_we0 = ap_const_logic_0;
    }
}

void matrix_mult::thread_i_1_fu_354_p2() {
    i_1_fu_354_p2 = (!i1_0_reg_168.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i1_0_reg_168.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void matrix_mult::thread_i_2_fu_587_p2() {
    i_2_fu_587_p2 = (!i3_0_reg_236.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i3_0_reg_236.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void matrix_mult::thread_i_fu_264_p2() {
    i_fu_264_p2 = (!i_0_reg_146.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(i_0_reg_146.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void matrix_mult::thread_icmp_ln16_fu_258_p2() {
    icmp_ln16_fu_258_p2 = (!i_0_reg_146.read().is_01() || !ap_const_lv5_14.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_146.read() == ap_const_lv5_14);
}

void matrix_mult::thread_icmp_ln17_fu_304_p2() {
    icmp_ln17_fu_304_p2 = (!j_0_reg_157.read().is_01() || !ap_const_lv5_14.is_01())? sc_lv<1>(): sc_lv<1>(j_0_reg_157.read() == ap_const_lv5_14);
}

void matrix_mult::thread_icmp_ln22_fu_348_p2() {
    icmp_ln22_fu_348_p2 = (!i1_0_reg_168.read().is_01() || !ap_const_lv5_14.is_01())? sc_lv<1>(): sc_lv<1>(i1_0_reg_168.read() == ap_const_lv5_14);
}

void matrix_mult::thread_icmp_ln23_fu_394_p2() {
    icmp_ln23_fu_394_p2 = (!j2_0_reg_179.read().is_01() || !ap_const_lv5_14.is_01())? sc_lv<1>(): sc_lv<1>(j2_0_reg_179.read() == ap_const_lv5_14);
}

void matrix_mult::thread_icmp_ln29_fu_438_p2() {
    icmp_ln29_fu_438_p2 = (!m_0_reg_190.read().is_01() || !ap_const_lv5_14.is_01())? sc_lv<1>(): sc_lv<1>(m_0_reg_190.read() == ap_const_lv5_14);
}

void matrix_mult::thread_icmp_ln30_fu_480_p2() {
    icmp_ln30_fu_480_p2 = (!o_0_reg_201.read().is_01() || !ap_const_lv5_14.is_01())? sc_lv<1>(): sc_lv<1>(o_0_reg_201.read() == ap_const_lv5_14);
}

void matrix_mult::thread_icmp_ln32_fu_506_p2() {
    icmp_ln32_fu_506_p2 = (!n_0_reg_225.read().is_01() || !ap_const_lv5_14.is_01())? sc_lv<1>(): sc_lv<1>(n_0_reg_225.read() == ap_const_lv5_14);
}

void matrix_mult::thread_icmp_ln40_fu_581_p2() {
    icmp_ln40_fu_581_p2 = (!i3_0_reg_236.read().is_01() || !ap_const_lv5_14.is_01())? sc_lv<1>(): sc_lv<1>(i3_0_reg_236.read() == ap_const_lv5_14);
}

void matrix_mult::thread_icmp_ln41_fu_627_p2() {
    icmp_ln41_fu_627_p2 = (!j4_0_reg_247.read().is_01() || !ap_const_lv5_14.is_01())? sc_lv<1>(): sc_lv<1>(j4_0_reg_247.read() == ap_const_lv5_14);
}

void matrix_mult::thread_j_1_fu_400_p2() {
    j_1_fu_400_p2 = (!j2_0_reg_179.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(j2_0_reg_179.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void matrix_mult::thread_j_2_fu_633_p2() {
    j_2_fu_633_p2 = (!j4_0_reg_247.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(j4_0_reg_247.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void matrix_mult::thread_j_fu_310_p2() {
    j_fu_310_p2 = (!j_0_reg_157.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(j_0_reg_157.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void matrix_mult::thread_m_fu_444_p2() {
    m_fu_444_p2 = (!m_0_reg_190.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(m_0_reg_190.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void matrix_mult::thread_mul_ln33_fu_572_p2() {
    mul_ln33_fu_572_p2 = (!b_buff_load_reg_808.read().is_01() || !a_buff_load_reg_803.read().is_01())? sc_lv<32>(): sc_bigint<32>(b_buff_load_reg_808.read()) * sc_bigint<32>(a_buff_load_reg_803.read());
}

void matrix_mult::thread_n_fu_512_p2() {
    n_fu_512_p2 = (!n_0_reg_225.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(n_0_reg_225.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void matrix_mult::thread_o_fu_486_p2() {
    o_fu_486_p2 = (!o_0_reg_201.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(o_0_reg_201.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void matrix_mult::thread_shl_ln18_1_fu_278_p3() {
    shl_ln18_1_fu_278_p3 = esl_concat<5,2>(i_0_reg_146.read(), ap_const_lv2_0);
}

void matrix_mult::thread_shl_ln1_fu_360_p3() {
    shl_ln1_fu_360_p3 = esl_concat<5,4>(i1_0_reg_168.read(), ap_const_lv4_0);
}

void matrix_mult::thread_shl_ln24_1_fu_368_p3() {
    shl_ln24_1_fu_368_p3 = esl_concat<5,2>(i1_0_reg_168.read(), ap_const_lv2_0);
}

void matrix_mult::thread_shl_ln_fu_270_p3() {
    shl_ln_fu_270_p3 = esl_concat<5,4>(i_0_reg_146.read(), ap_const_lv4_0);
}

void matrix_mult::thread_tmp_4_fu_450_p3() {
    tmp_4_fu_450_p3 = esl_concat<5,4>(m_0_reg_190.read(), ap_const_lv4_0);
}

void matrix_mult::thread_tmp_5_fu_462_p3() {
    tmp_5_fu_462_p3 = esl_concat<5,2>(m_0_reg_190.read(), ap_const_lv2_0);
}

void matrix_mult::thread_tmp_6_fu_593_p3() {
    tmp_6_fu_593_p3 = esl_concat<5,4>(i3_0_reg_236.read(), ap_const_lv4_0);
}

void matrix_mult::thread_tmp_7_fu_605_p3() {
    tmp_7_fu_605_p3 = esl_concat<5,2>(i3_0_reg_236.read(), ap_const_lv2_0);
}

void matrix_mult::thread_tmp_8_fu_532_p3() {
    tmp_8_fu_532_p3 = esl_concat<5,4>(n_0_reg_225.read(), ap_const_lv4_0);
}

void matrix_mult::thread_tmp_9_fu_544_p3() {
    tmp_9_fu_544_p3 = esl_concat<5,2>(n_0_reg_225.read(), ap_const_lv2_0);
}

void matrix_mult::thread_zext_ln17_fu_300_p1() {
    zext_ln17_fu_300_p1 = esl_zext<7,5>(j_0_reg_157.read());
}

void matrix_mult::thread_zext_ln18_1_fu_330_p1() {
    zext_ln18_1_fu_330_p1 = esl_zext<64,9>(add_ln18_fu_325_p2.read());
}

void matrix_mult::thread_zext_ln18_2_fu_290_p1() {
    zext_ln18_2_fu_290_p1 = esl_zext<10,7>(shl_ln18_1_fu_278_p3.read());
}

void matrix_mult::thread_zext_ln18_3_fu_321_p1() {
    zext_ln18_3_fu_321_p1 = esl_zext<9,7>(add_ln18_1_fu_316_p2.read());
}

void matrix_mult::thread_zext_ln18_4_fu_335_p1() {
    zext_ln18_4_fu_335_p1 = esl_zext<10,5>(j_0_reg_157.read());
}

void matrix_mult::thread_zext_ln18_5_fu_344_p1() {
    zext_ln18_5_fu_344_p1 = esl_zext<64,10>(add_ln18_3_reg_707.read());
}

void matrix_mult::thread_zext_ln18_fu_286_p1() {
    zext_ln18_fu_286_p1 = esl_zext<10,9>(shl_ln_fu_270_p3.read());
}

void matrix_mult::thread_zext_ln23_fu_390_p1() {
    zext_ln23_fu_390_p1 = esl_zext<7,5>(j2_0_reg_179.read());
}

void matrix_mult::thread_zext_ln24_1_fu_420_p1() {
    zext_ln24_1_fu_420_p1 = esl_zext<64,9>(add_ln24_fu_415_p2.read());
}

void matrix_mult::thread_zext_ln24_2_fu_380_p1() {
    zext_ln24_2_fu_380_p1 = esl_zext<10,7>(shl_ln24_1_fu_368_p3.read());
}

void matrix_mult::thread_zext_ln24_3_fu_411_p1() {
    zext_ln24_3_fu_411_p1 = esl_zext<9,7>(add_ln24_1_fu_406_p2.read());
}

void matrix_mult::thread_zext_ln24_4_fu_425_p1() {
    zext_ln24_4_fu_425_p1 = esl_zext<10,5>(j2_0_reg_179.read());
}

void matrix_mult::thread_zext_ln24_5_fu_434_p1() {
    zext_ln24_5_fu_434_p1 = esl_zext<64,10>(add_ln24_3_reg_748.read());
}

void matrix_mult::thread_zext_ln24_fu_376_p1() {
    zext_ln24_fu_376_p1 = esl_zext<10,9>(shl_ln1_fu_360_p3.read());
}

void matrix_mult::thread_zext_ln33_1_fu_470_p1() {
    zext_ln33_1_fu_470_p1 = esl_zext<10,7>(tmp_5_fu_462_p3.read());
}

void matrix_mult::thread_zext_ln33_2_fu_518_p1() {
    zext_ln33_2_fu_518_p1 = esl_zext<10,5>(n_0_reg_225.read());
}

void matrix_mult::thread_zext_ln33_3_fu_527_p1() {
    zext_ln33_3_fu_527_p1 = esl_zext<64,10>(add_ln33_1_fu_522_p2.read());
}

void matrix_mult::thread_zext_ln33_4_fu_540_p1() {
    zext_ln33_4_fu_540_p1 = esl_zext<10,9>(tmp_8_fu_532_p3.read());
}

void matrix_mult::thread_zext_ln33_5_fu_552_p1() {
    zext_ln33_5_fu_552_p1 = esl_zext<10,7>(tmp_9_fu_544_p3.read());
}

void matrix_mult::thread_zext_ln33_6_fu_567_p1() {
    zext_ln33_6_fu_567_p1 = esl_zext<64,10>(add_ln33_3_fu_562_p2.read());
}

void matrix_mult::thread_zext_ln33_fu_458_p1() {
    zext_ln33_fu_458_p1 = esl_zext<10,9>(tmp_4_fu_450_p3.read());
}

void matrix_mult::thread_zext_ln35_1_fu_501_p1() {
    zext_ln35_1_fu_501_p1 = esl_zext<64,10>(add_ln35_fu_496_p2.read());
}

void matrix_mult::thread_zext_ln35_fu_492_p1() {
    zext_ln35_fu_492_p1 = esl_zext<10,5>(o_0_reg_201.read());
}

void matrix_mult::thread_zext_ln41_fu_623_p1() {
    zext_ln41_fu_623_p1 = esl_zext<7,5>(j4_0_reg_247.read());
}

void matrix_mult::thread_zext_ln42_1_fu_613_p1() {
    zext_ln42_1_fu_613_p1 = esl_zext<10,7>(tmp_7_fu_605_p3.read());
}

void matrix_mult::thread_zext_ln42_2_fu_667_p1() {
    zext_ln42_2_fu_667_p1 = esl_zext<64,9>(add_ln42_reg_859.read());
}

void matrix_mult::thread_zext_ln42_3_fu_658_p1() {
    zext_ln42_3_fu_658_p1 = esl_zext<9,7>(add_ln42_1_fu_653_p2.read());
}

void matrix_mult::thread_zext_ln42_4_fu_639_p1() {
    zext_ln42_4_fu_639_p1 = esl_zext<10,5>(j4_0_reg_247.read());
}

void matrix_mult::thread_zext_ln42_5_fu_648_p1() {
    zext_ln42_5_fu_648_p1 = esl_zext<64,10>(add_ln42_3_fu_643_p2.read());
}

void matrix_mult::thread_zext_ln42_fu_601_p1() {
    zext_ln42_fu_601_p1 = esl_zext<10,9>(tmp_6_fu_593_p3.read());
}

void matrix_mult::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln16_fu_258_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(icmp_ln17_fu_304_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(icmp_ln22_fu_348_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(icmp_ln23_fu_394_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(icmp_ln29_fu_438_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state14;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 256 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && esl_seteq<1,1,1>(icmp_ln30_fu_480_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state8;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 512 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) && esl_seteq<1,1,1>(icmp_ln32_fu_506_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 8192 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) && esl_seteq<1,1,1>(icmp_ln40_fu_581_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state15;
            }
            break;
        case 16384 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) && esl_seteq<1,1,1>(icmp_ln41_fu_627_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state14;
            } else {
                ap_NS_fsm = ap_ST_fsm_state16;
            }
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
            break;
    }
}

void matrix_mult::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"a_address0\" :  \"" << a_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"a_ce0\" :  \"" << a_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"a_q0\" :  \"" << a_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"b_address0\" :  \"" << b_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"b_ce0\" :  \"" << b_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"b_q0\" :  \"" << b_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"c_address0\" :  \"" << c_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"c_ce0\" :  \"" << c_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"c_we0\" :  \"" << c_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"c_d0\" :  \"" << c_d0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

