// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="block_mmul,hls_ip_2019_2_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=9.634000,HLS_SYN_LAT=1000019,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=16,HLS_SYN_FF=1066,HLS_SYN_LUT=1460,HLS_VERSION=2019_2_1}" *)

module block_mmul (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_address0,
        A_ce0,
        A_q0,
        B_address0,
        B_ce0,
        B_q0,
        B_address1,
        B_ce1,
        B_q1,
        out_r_address0,
        out_r_ce0,
        out_r_we0,
        out_r_d0,
        out_r_q0,
        out_r_address1,
        out_r_ce1,
        out_r_we1,
        out_r_d1,
        out_r_q1
);

parameter    ap_ST_fsm_state1 = 18'd1;
parameter    ap_ST_fsm_pp0_stage0 = 18'd2;
parameter    ap_ST_fsm_pp0_stage1 = 18'd4;
parameter    ap_ST_fsm_pp0_stage2 = 18'd8;
parameter    ap_ST_fsm_pp0_stage3 = 18'd16;
parameter    ap_ST_fsm_pp0_stage4 = 18'd32;
parameter    ap_ST_fsm_pp0_stage5 = 18'd64;
parameter    ap_ST_fsm_pp0_stage6 = 18'd128;
parameter    ap_ST_fsm_pp0_stage7 = 18'd256;
parameter    ap_ST_fsm_pp0_stage8 = 18'd512;
parameter    ap_ST_fsm_pp0_stage9 = 18'd1024;
parameter    ap_ST_fsm_pp0_stage10 = 18'd2048;
parameter    ap_ST_fsm_pp0_stage11 = 18'd4096;
parameter    ap_ST_fsm_pp0_stage12 = 18'd8192;
parameter    ap_ST_fsm_pp0_stage13 = 18'd16384;
parameter    ap_ST_fsm_pp0_stage14 = 18'd32768;
parameter    ap_ST_fsm_pp0_stage15 = 18'd65536;
parameter    ap_ST_fsm_state36 = 18'd131072;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [13:0] A_address0;
output   A_ce0;
input  [15:0] A_q0;
output  [13:0] B_address0;
output   B_ce0;
input  [15:0] B_q0;
output  [13:0] B_address1;
output   B_ce1;
input  [15:0] B_q1;
output  [13:0] out_r_address0;
output   out_r_ce0;
output   out_r_we0;
output  [15:0] out_r_d0;
input  [15:0] out_r_q0;
output  [13:0] out_r_address1;
output   out_r_ce1;
output   out_r_we1;
output  [15:0] out_r_d1;
input  [15:0] out_r_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[13:0] A_address0;
reg A_ce0;
reg[13:0] B_address0;
reg B_ce0;
reg[13:0] B_address1;
reg B_ce1;
reg[13:0] out_r_address0;
reg out_r_ce0;
reg out_r_we0;
reg[15:0] out_r_d0;
reg[13:0] out_r_address1;
reg out_r_ce1;
reg out_r_we1;
reg[15:0] out_r_d1;

(* fsm_encoding = "none" *) reg   [17:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [15:0] indvar_flatten29_reg_273;
reg   [6:0] k_0_reg_284;
reg   [9:0] indvar_flatten_reg_295;
reg   [6:0] ii_0_reg_306;
reg   [6:0] jj_0_reg_317;
reg   [15:0] reg_328;
wire    ap_CS_fsm_pp0_stage3;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_state5_pp0_stage3_iter0;
wire    ap_block_state21_pp0_stage3_iter1;
wire    ap_block_pp0_stage3_11001;
reg   [0:0] icmp_ln37_reg_922;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_state6_pp0_stage4_iter0;
wire    ap_block_state22_pp0_stage4_iter1;
wire    ap_block_pp0_stage4_11001;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_state8_pp0_stage6_iter0;
wire    ap_block_state24_pp0_stage6_iter1;
wire    ap_block_pp0_stage6_11001;
wire    ap_CS_fsm_pp0_stage10;
wire    ap_block_state12_pp0_stage10_iter0;
wire    ap_block_state28_pp0_stage10_iter1;
wire    ap_block_pp0_stage10_11001;
reg   [15:0] reg_332;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_state7_pp0_stage5_iter0;
wire    ap_block_state23_pp0_stage5_iter1;
wire    ap_block_pp0_stage5_11001;
wire    ap_CS_fsm_pp0_stage8;
wire    ap_block_state10_pp0_stage8_iter0;
wire    ap_block_state26_pp0_stage8_iter1;
wire    ap_block_pp0_stage8_11001;
reg   [15:0] reg_337;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_state9_pp0_stage7_iter0;
wire    ap_block_state25_pp0_stage7_iter1;
wire    ap_block_pp0_stage7_11001;
reg   [15:0] reg_342;
wire    ap_CS_fsm_pp0_stage9;
wire    ap_block_state11_pp0_stage9_iter0;
wire    ap_block_state27_pp0_stage9_iter1;
wire    ap_block_pp0_stage9_11001;
wire   [0:0] icmp_ln37_fu_365_p2;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state2_pp0_stage0_iter0;
wire    ap_block_state18_pp0_stage0_iter1;
wire    ap_block_state34_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln37_reg_922_pp0_iter1_reg;
reg   [0:0] icmp_ln37_reg_922_pp0_iter2_reg;
wire   [15:0] add_ln37_fu_371_p2;
reg   [15:0] add_ln37_reg_926;
wire   [6:0] select_ln43_2_fu_405_p3;
reg   [6:0] select_ln43_2_reg_931;
wire   [13:0] mul_ln43_16_fu_417_p2;
reg   [13:0] mul_ln43_16_reg_937;
wire   [6:0] select_ln43_6_fu_465_p3;
reg   [6:0] select_ln43_6_reg_945;
wire   [6:0] select_ln43_7_fu_473_p3;
reg   [6:0] select_ln43_7_reg_954;
wire   [6:0] select_ln43_8_fu_487_p3;
reg   [6:0] select_ln43_8_reg_960;
wire   [6:0] select_ln43_9_fu_501_p3;
reg   [6:0] select_ln43_9_reg_965;
wire   [6:0] select_ln43_10_fu_515_p3;
reg   [6:0] select_ln43_10_reg_970;
wire   [9:0] select_ln38_fu_529_p3;
reg   [9:0] select_ln38_reg_975;
wire   [13:0] mul_ln43_17_fu_540_p2;
reg   [13:0] mul_ln43_17_reg_980;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state3_pp0_stage1_iter0;
wire    ap_block_state19_pp0_stage1_iter1;
wire    ap_block_state35_pp0_stage1_iter2;
wire    ap_block_pp0_stage1_11001;
wire   [13:0] zext_ln43_10_fu_546_p1;
reg   [13:0] zext_ln43_10_reg_989;
wire   [13:0] zext_ln43_16_fu_564_p1;
reg   [13:0] zext_ln43_16_reg_1002;
wire   [13:0] zext_ln43_fu_578_p1;
reg   [13:0] zext_ln43_reg_1015;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state4_pp0_stage2_iter0;
wire    ap_block_state20_pp0_stage2_iter1;
wire    ap_block_pp0_stage2_11001;
wire   [13:0] mul_ln43_18_fu_594_p2;
reg   [13:0] mul_ln43_18_reg_1027;
reg   [13:0] out_addr_reg_1036;
reg  signed [15:0] B_load_reg_1041;
reg   [13:0] out_addr_1_reg_1049;
reg  signed [15:0] B_load_1_reg_1054;
wire   [13:0] zext_ln43_22_fu_623_p1;
reg   [13:0] zext_ln43_22_reg_1062;
wire   [13:0] zext_ln43_28_fu_642_p1;
reg   [13:0] zext_ln43_28_reg_1075;
wire   [13:0] mul_ln43_19_fu_668_p2;
reg   [13:0] mul_ln43_19_reg_1093;
reg  signed [15:0] A_load_reg_1102;
reg   [13:0] out_addr_2_reg_1110;
reg  signed [15:0] B_load_2_reg_1115;
reg   [13:0] out_addr_3_reg_1123;
reg  signed [15:0] B_load_3_reg_1128;
wire   [13:0] mul_ln43_20_fu_704_p2;
reg   [13:0] mul_ln43_20_reg_1141;
reg   [13:0] out_addr_4_reg_1150;
wire  signed [15:0] grp_fu_828_p3;
reg  signed [15:0] add_ln43_reg_1155;
reg   [13:0] out_addr_5_reg_1160;
reg  signed [15:0] A_load_1_reg_1165;
wire  signed [15:0] grp_fu_834_p3;
reg  signed [15:0] add_ln43_1_reg_1178;
reg   [13:0] out_addr_6_reg_1183;
reg   [13:0] out_addr_7_reg_1188;
reg  signed [15:0] A_load_2_reg_1193;
reg   [13:0] out_addr_8_reg_1201;
reg   [13:0] out_addr_9_reg_1206;
wire  signed [15:0] grp_fu_840_p3;
reg  signed [15:0] add_ln43_2_reg_1211;
reg   [15:0] out_load_7_reg_1216;
reg  signed [15:0] A_load_3_reg_1221;
wire   [13:0] add_ln43_24_fu_773_p2;
reg   [13:0] add_ln43_24_reg_1229;
wire   [13:0] add_ln43_29_fu_777_p2;
reg   [13:0] add_ln43_29_reg_1234;
reg   [13:0] out_addr_10_reg_1239;
wire   [13:0] add_ln43_34_fu_790_p2;
reg   [13:0] add_ln43_34_reg_1244;
reg   [13:0] out_addr_11_reg_1249;
wire   [13:0] add_ln43_39_fu_803_p2;
reg   [13:0] add_ln43_39_reg_1254;
wire  signed [15:0] grp_fu_846_p3;
reg  signed [15:0] add_ln43_3_reg_1259;
reg   [15:0] out_load_9_reg_1264;
reg   [13:0] out_addr_12_reg_1269;
reg   [13:0] out_addr_13_reg_1274;
wire  signed [15:0] grp_fu_852_p3;
reg  signed [15:0] add_ln43_4_reg_1280;
reg   [15:0] out_load_11_reg_1285;
reg   [13:0] out_addr_14_reg_1290;
reg   [13:0] out_addr_14_reg_1290_pp0_iter1_reg;
reg   [13:0] out_addr_15_reg_1296;
reg   [13:0] out_addr_15_reg_1296_pp0_iter1_reg;
wire  signed [15:0] grp_fu_858_p3;
reg  signed [15:0] add_ln43_5_reg_1301;
reg   [15:0] out_load_13_reg_1306;
wire  signed [15:0] grp_fu_864_p3;
reg  signed [15:0] add_ln43_6_reg_1311;
reg   [15:0] out_load_15_reg_1316;
wire  signed [15:0] grp_fu_870_p3;
reg  signed [15:0] add_ln43_7_reg_1321;
wire    ap_CS_fsm_pp0_stage11;
wire    ap_block_state13_pp0_stage11_iter0;
wire    ap_block_state29_pp0_stage11_iter1;
wire    ap_block_pp0_stage11_11001;
wire  signed [15:0] grp_fu_875_p3;
reg  signed [15:0] add_ln43_8_reg_1326;
wire    ap_CS_fsm_pp0_stage12;
wire    ap_block_state14_pp0_stage12_iter0;
wire    ap_block_state30_pp0_stage12_iter1;
wire    ap_block_pp0_stage12_11001;
wire  signed [15:0] grp_fu_881_p3;
reg  signed [15:0] add_ln43_9_reg_1331;
wire    ap_CS_fsm_pp0_stage13;
wire    ap_block_state15_pp0_stage13_iter0;
wire    ap_block_state31_pp0_stage13_iter1;
wire    ap_block_pp0_stage13_11001;
wire  signed [15:0] grp_fu_886_p3;
reg  signed [15:0] add_ln43_10_reg_1336;
wire    ap_CS_fsm_pp0_stage14;
wire    ap_block_state16_pp0_stage14_iter0;
wire    ap_block_state32_pp0_stage14_iter1;
wire    ap_block_pp0_stage14_11001;
wire   [6:0] jj_fu_823_p2;
reg   [6:0] jj_reg_1341;
wire    ap_CS_fsm_pp0_stage15;
wire    ap_block_state17_pp0_stage15_iter0;
wire    ap_block_state33_pp0_stage15_iter1;
wire    ap_block_pp0_stage15_11001;
wire  signed [15:0] grp_fu_911_p3;
reg  signed [15:0] add_ln43_14_reg_1346;
reg    ap_enable_reg_pp0_iter1;
wire  signed [15:0] grp_fu_917_p3;
reg  signed [15:0] add_ln43_15_reg_1351;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state2;
wire    ap_block_pp0_stage15_subdone;
wire    ap_block_pp0_stage1_subdone;
reg    ap_enable_reg_pp0_iter2;
reg   [15:0] ap_phi_mux_indvar_flatten29_phi_fu_277_p4;
wire    ap_block_pp0_stage0;
reg   [6:0] ap_phi_mux_k_0_phi_fu_288_p4;
reg   [9:0] ap_phi_mux_indvar_flatten_phi_fu_299_p4;
reg   [6:0] ap_phi_mux_ii_0_phi_fu_310_p4;
reg   [6:0] ap_phi_mux_jj_0_phi_fu_321_p4;
wire   [63:0] zext_ln43_11_fu_554_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln43_17_fu_573_p1;
wire   [63:0] zext_ln43_3_fu_586_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln43_12_fu_604_p1;
wire   [63:0] zext_ln43_18_fu_613_p1;
wire   [63:0] zext_ln43_23_fu_632_p1;
wire   [63:0] zext_ln43_29_fu_651_p1;
wire   [63:0] zext_ln43_5_fu_660_p1;
wire    ap_block_pp0_stage3;
wire   [63:0] zext_ln43_24_fu_678_p1;
wire   [63:0] zext_ln43_30_fu_687_p1;
wire   [63:0] zext_ln43_7_fu_696_p1;
wire    ap_block_pp0_stage4;
wire   [63:0] zext_ln43_13_fu_714_p1;
wire   [63:0] zext_ln43_19_fu_723_p1;
wire   [63:0] zext_ln43_9_fu_732_p1;
wire    ap_block_pp0_stage5;
wire   [63:0] zext_ln43_25_fu_741_p1;
wire   [63:0] zext_ln43_31_fu_750_p1;
wire   [63:0] zext_ln43_14_fu_759_p1;
wire    ap_block_pp0_stage6;
wire   [63:0] zext_ln43_20_fu_768_p1;
wire   [63:0] zext_ln43_26_fu_785_p1;
wire    ap_block_pp0_stage7;
wire   [63:0] zext_ln43_32_fu_798_p1;
wire   [63:0] zext_ln43_15_fu_807_p1;
wire    ap_block_pp0_stage8;
wire   [63:0] zext_ln43_21_fu_811_p1;
wire   [63:0] zext_ln43_27_fu_815_p1;
wire    ap_block_pp0_stage9;
wire   [63:0] zext_ln43_33_fu_819_p1;
wire    ap_block_pp0_stage10;
wire    ap_block_pp0_stage11;
wire    ap_block_pp0_stage12;
wire    ap_block_pp0_stage13;
wire    ap_block_pp0_stage14;
wire    ap_block_pp0_stage15;
wire  signed [15:0] grp_fu_892_p3;
wire  signed [15:0] grp_fu_898_p3;
wire  signed [15:0] grp_fu_905_p3;
wire   [0:0] icmp_ln38_fu_383_p2;
wire   [6:0] k_fu_377_p2;
wire   [6:0] mul_ln43_16_fu_417_p0;
wire   [6:0] or_ln43_3_fu_347_p2;
wire   [6:0] or_ln43_4_fu_353_p2;
wire   [6:0] or_ln43_5_fu_359_p2;
wire   [0:0] icmp_ln39_fu_447_p2;
wire   [6:0] select_ln43_fu_389_p3;
wire   [0:0] or_ln43_6_fu_453_p2;
wire   [6:0] select_ln43_1_fu_397_p3;
wire   [6:0] ii_fu_459_p2;
wire   [6:0] select_ln43_3_fu_423_p3;
wire   [6:0] or_ln43_7_fu_481_p2;
wire   [6:0] select_ln43_4_fu_431_p3;
wire   [6:0] or_ln43_8_fu_495_p2;
wire   [6:0] select_ln43_5_fu_439_p3;
wire   [6:0] or_ln43_9_fu_509_p2;
wire   [9:0] add_ln38_1_fu_523_p2;
wire   [6:0] mul_ln43_17_fu_540_p0;
wire   [13:0] add_ln43_20_fu_549_p2;
wire   [6:0] or_ln43_fu_559_p2;
wire   [13:0] add_ln43_25_fu_568_p2;
wire   [13:0] add_ln43_16_fu_581_p2;
wire   [6:0] mul_ln43_18_fu_594_p0;
wire   [13:0] add_ln43_21_fu_600_p2;
wire   [13:0] add_ln43_26_fu_609_p2;
wire   [6:0] or_ln43_1_fu_618_p2;
wire   [13:0] add_ln43_30_fu_627_p2;
wire   [6:0] or_ln43_2_fu_637_p2;
wire   [13:0] add_ln43_35_fu_646_p2;
wire   [13:0] add_ln43_17_fu_656_p2;
wire   [6:0] mul_ln43_19_fu_668_p0;
wire   [13:0] add_ln43_31_fu_674_p2;
wire   [13:0] add_ln43_36_fu_683_p2;
wire   [13:0] add_ln43_18_fu_692_p2;
wire   [6:0] mul_ln43_20_fu_704_p0;
wire   [13:0] add_ln43_22_fu_710_p2;
wire   [13:0] add_ln43_27_fu_719_p2;
wire   [13:0] add_ln43_19_fu_728_p2;
wire   [13:0] add_ln43_32_fu_737_p2;
wire   [13:0] add_ln43_37_fu_746_p2;
wire   [13:0] add_ln43_23_fu_755_p2;
wire   [13:0] add_ln43_28_fu_764_p2;
wire   [13:0] add_ln43_33_fu_781_p2;
wire   [13:0] add_ln43_38_fu_794_p2;
wire    ap_CS_fsm_state36;
reg   [17:0] ap_NS_fsm;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_block_pp0_stage7_subdone;
wire    ap_block_pp0_stage8_subdone;
wire    ap_block_pp0_stage9_subdone;
wire    ap_block_pp0_stage10_subdone;
wire    ap_block_pp0_stage11_subdone;
wire    ap_block_pp0_stage12_subdone;
wire    ap_block_pp0_stage13_subdone;
wire    ap_block_pp0_stage14_subdone;
reg    ap_idle_pp0;
wire    ap_enable_pp0;
wire   [13:0] mul_ln43_16_fu_417_p00;
wire   [13:0] mul_ln43_17_fu_540_p00;
wire   [13:0] mul_ln43_18_fu_594_p00;
wire   [13:0] mul_ln43_19_fu_668_p00;
wire   [13:0] mul_ln43_20_fu_704_p00;

// power-on initialization
initial begin
#0 ap_CS_fsm = 18'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

block_mmul_mac_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
block_mmul_mac_mubkb_U1(
    .din0(B_load_reg_1041),
    .din1(A_load_reg_1102),
    .din2(reg_328),
    .dout(grp_fu_828_p3)
);

block_mmul_mac_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
block_mmul_mac_mubkb_U2(
    .din0(B_load_1_reg_1054),
    .din1(A_load_reg_1102),
    .din2(reg_332),
    .dout(grp_fu_834_p3)
);

block_mmul_mac_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
block_mmul_mac_mubkb_U3(
    .din0(B_load_2_reg_1115),
    .din1(A_load_reg_1102),
    .din2(reg_328),
    .dout(grp_fu_840_p3)
);

block_mmul_mac_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
block_mmul_mac_mubkb_U4(
    .din0(B_load_3_reg_1128),
    .din1(A_load_reg_1102),
    .din2(reg_337),
    .dout(grp_fu_846_p3)
);

block_mmul_mac_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
block_mmul_mac_mubkb_U5(
    .din0(B_load_reg_1041),
    .din1(A_load_1_reg_1165),
    .din2(reg_332),
    .dout(grp_fu_852_p3)
);

block_mmul_mac_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
block_mmul_mac_mubkb_U6(
    .din0(B_load_1_reg_1054),
    .din1(A_load_1_reg_1165),
    .din2(reg_342),
    .dout(grp_fu_858_p3)
);

block_mmul_mac_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
block_mmul_mac_mubkb_U7(
    .din0(B_load_2_reg_1115),
    .din1(A_load_1_reg_1165),
    .din2(reg_328),
    .dout(grp_fu_864_p3)
);

block_mmul_mac_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
block_mmul_mac_mubkb_U8(
    .din0(B_load_3_reg_1128),
    .din1(A_load_1_reg_1165),
    .din2(out_load_7_reg_1216),
    .dout(grp_fu_870_p3)
);

block_mmul_mac_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
block_mmul_mac_mubkb_U9(
    .din0(B_load_reg_1041),
    .din1(A_load_2_reg_1193),
    .din2(reg_337),
    .dout(grp_fu_875_p3)
);

block_mmul_mac_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
block_mmul_mac_mubkb_U10(
    .din0(B_load_1_reg_1054),
    .din1(A_load_2_reg_1193),
    .din2(out_load_9_reg_1264),
    .dout(grp_fu_881_p3)
);

block_mmul_mac_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
block_mmul_mac_mubkb_U11(
    .din0(B_load_2_reg_1115),
    .din1(A_load_2_reg_1193),
    .din2(reg_332),
    .dout(grp_fu_886_p3)
);

block_mmul_mac_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
block_mmul_mac_mubkb_U12(
    .din0(B_load_3_reg_1128),
    .din1(A_load_2_reg_1193),
    .din2(out_load_11_reg_1285),
    .dout(grp_fu_892_p3)
);

block_mmul_mac_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
block_mmul_mac_mubkb_U13(
    .din0(B_load_reg_1041),
    .din1(A_load_3_reg_1221),
    .din2(reg_342),
    .dout(grp_fu_898_p3)
);

block_mmul_mac_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
block_mmul_mac_mubkb_U14(
    .din0(B_load_1_reg_1054),
    .din1(A_load_3_reg_1221),
    .din2(out_load_13_reg_1306),
    .dout(grp_fu_905_p3)
);

block_mmul_mac_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
block_mmul_mac_mubkb_U15(
    .din0(B_load_2_reg_1115),
    .din1(A_load_3_reg_1221),
    .din2(reg_328),
    .dout(grp_fu_911_p3)
);

block_mmul_mac_mubkb #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .din2_WIDTH( 16 ),
    .dout_WIDTH( 16 ))
block_mmul_mac_mubkb_U16(
    .din0(B_load_3_reg_1128),
    .din1(A_load_3_reg_1221),
    .din2(out_load_15_reg_1316),
    .dout(grp_fu_917_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state2) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage15_subdone) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((((1'b0 == ap_block_pp0_stage15_subdone) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((1'b0 == ap_block_pp0_stage1_subdone) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_enable_reg_pp0_iter2 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ii_0_reg_306 <= select_ln43_7_reg_954;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ii_0_reg_306 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten29_reg_273 <= add_ln37_reg_926;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten29_reg_273 <= 16'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        indvar_flatten_reg_295 <= select_ln38_reg_975;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        indvar_flatten_reg_295 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        jj_0_reg_317 <= jj_reg_1341;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        jj_0_reg_317 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        k_0_reg_284 <= select_ln43_2_reg_931;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        k_0_reg_284 <= 7'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln37_reg_922 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001)) | ((icmp_ln37_reg_922 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)))) begin
        reg_332 <= out_r_q0;
    end else if (((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        reg_332 <= out_r_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001))) begin
            reg_337 <= out_r_q0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001))) begin
            reg_337 <= out_r_q1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        if (((1'b1 == ap_CS_fsm_pp0_stage9) & (1'b0 == ap_block_pp0_stage9_11001))) begin
            reg_342 <= out_r_q0;
        end else if (((1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001))) begin
            reg_342 <= out_r_q1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        A_load_1_reg_1165 <= A_q0;
        add_ln43_reg_1155 <= grp_fu_828_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001))) begin
        A_load_2_reg_1193 <= A_q0;
        add_ln43_1_reg_1178 <= grp_fu_834_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001))) begin
        A_load_3_reg_1221 <= A_q0;
        add_ln43_2_reg_1211 <= grp_fu_840_p3;
        out_load_7_reg_1216 <= out_r_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        A_load_reg_1102 <= A_q0;
        B_load_2_reg_1115 <= B_q0;
        B_load_3_reg_1128 <= B_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        B_load_1_reg_1054 <= B_q1;
        B_load_reg_1041 <= B_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln37_reg_926 <= add_ln37_fu_371_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage14_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        add_ln43_10_reg_1336 <= grp_fu_886_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        add_ln43_14_reg_1346 <= grp_fu_911_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
        add_ln43_15_reg_1351 <= grp_fu_917_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001))) begin
        add_ln43_24_reg_1229 <= add_ln43_24_fu_773_p2;
        add_ln43_29_reg_1234[13 : 1] <= add_ln43_29_fu_777_p2[13 : 1];
        add_ln43_34_reg_1244 <= add_ln43_34_fu_790_p2;
        add_ln43_39_reg_1254[13 : 2] <= add_ln43_39_fu_803_p2[13 : 2];
        out_addr_10_reg_1239 <= zext_ln43_26_fu_785_p1;
        out_addr_11_reg_1249[13 : 2] <= zext_ln43_32_fu_798_p1[13 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001))) begin
        add_ln43_3_reg_1259 <= grp_fu_846_p3;
        out_load_9_reg_1264 <= out_r_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001))) begin
        add_ln43_4_reg_1280 <= grp_fu_852_p3;
        out_load_11_reg_1285 <= out_r_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9) & (1'b0 == ap_block_pp0_stage9_11001))) begin
        add_ln43_5_reg_1301 <= grp_fu_858_p3;
        out_load_13_reg_1306 <= out_r_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10) & (1'b0 == ap_block_pp0_stage10_11001))) begin
        add_ln43_6_reg_1311 <= grp_fu_864_p3;
        out_load_15_reg_1316 <= out_r_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage11_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        add_ln43_7_reg_1321 <= grp_fu_870_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        add_ln43_8_reg_1326 <= grp_fu_875_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage13_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        add_ln43_9_reg_1331 <= grp_fu_881_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln37_reg_922 <= icmp_ln37_fu_365_p2;
        icmp_ln37_reg_922_pp0_iter1_reg <= icmp_ln37_reg_922;
        icmp_ln37_reg_922_pp0_iter2_reg <= icmp_ln37_reg_922_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage15_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        jj_reg_1341 <= jj_fu_823_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_fu_365_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul_ln43_16_reg_937[13 : 2] <= mul_ln43_16_fu_417_p2[13 : 2];
        select_ln43_10_reg_970[6 : 2] <= select_ln43_10_fu_515_p3[6 : 2];
        select_ln43_6_reg_945 <= select_ln43_6_fu_465_p3;
        select_ln43_8_reg_960[6 : 1] <= select_ln43_8_fu_487_p3[6 : 1];
        select_ln43_9_reg_965[0] <= select_ln43_9_fu_501_p3[0];
select_ln43_9_reg_965[6 : 2] <= select_ln43_9_fu_501_p3[6 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        mul_ln43_17_reg_980[13 : 2] <= mul_ln43_17_fu_540_p2[13 : 2];
        zext_ln43_10_reg_989[6 : 0] <= zext_ln43_10_fu_546_p1[6 : 0];
        zext_ln43_16_reg_1002[6 : 1] <= zext_ln43_16_fu_564_p1[6 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        mul_ln43_18_reg_1027[13 : 2] <= mul_ln43_18_fu_594_p2[13 : 2];
        out_addr_1_reg_1049[13 : 1] <= zext_ln43_18_fu_613_p1[13 : 1];
        out_addr_reg_1036 <= zext_ln43_12_fu_604_p1;
        zext_ln43_22_reg_1062[0] <= zext_ln43_22_fu_623_p1[0];
zext_ln43_22_reg_1062[6 : 2] <= zext_ln43_22_fu_623_p1[6 : 2];
        zext_ln43_28_reg_1075[6 : 2] <= zext_ln43_28_fu_642_p1[6 : 2];
        zext_ln43_reg_1015[6 : 0] <= zext_ln43_fu_578_p1[6 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        mul_ln43_19_reg_1093[13 : 2] <= mul_ln43_19_fu_668_p2[13 : 2];
        out_addr_2_reg_1110 <= zext_ln43_24_fu_678_p1;
        out_addr_3_reg_1123[13 : 2] <= zext_ln43_30_fu_687_p1[13 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4) & (1'b0 == ap_block_pp0_stage4_11001))) begin
        mul_ln43_20_reg_1141[13 : 2] <= mul_ln43_20_fu_704_p2[13 : 2];
        out_addr_4_reg_1150 <= zext_ln43_13_fu_714_p1;
        out_addr_5_reg_1160[13 : 1] <= zext_ln43_19_fu_723_p1[13 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001))) begin
        out_addr_12_reg_1269 <= zext_ln43_15_fu_807_p1;
        out_addr_13_reg_1274[13 : 1] <= zext_ln43_21_fu_811_p1[13 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage9) & (1'b0 == ap_block_pp0_stage9_11001))) begin
        out_addr_14_reg_1290 <= zext_ln43_27_fu_815_p1;
        out_addr_15_reg_1296[13 : 2] <= zext_ln43_33_fu_819_p1[13 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage9) & (1'b0 == ap_block_pp0_stage9_11001))) begin
        out_addr_14_reg_1290_pp0_iter1_reg <= out_addr_14_reg_1290;
        out_addr_15_reg_1296_pp0_iter1_reg[13 : 2] <= out_addr_15_reg_1296[13 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001))) begin
        out_addr_6_reg_1183 <= zext_ln43_25_fu_741_p1;
        out_addr_7_reg_1188[13 : 2] <= zext_ln43_31_fu_750_p1[13 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001))) begin
        out_addr_8_reg_1201 <= zext_ln43_14_fu_759_p1;
        out_addr_9_reg_1206[13 : 1] <= zext_ln43_20_fu_768_p1[13 : 1];
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln37_reg_922 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10) & (1'b0 == ap_block_pp0_stage10_11001)) | ((icmp_ln37_reg_922 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)) | ((icmp_ln37_reg_922 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001)) | ((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        reg_328 <= out_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_fu_365_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln38_reg_975 <= select_ln38_fu_529_p3;
        select_ln43_2_reg_931 <= select_ln43_2_fu_405_p3;
        select_ln43_7_reg_954 <= select_ln43_7_fu_473_p3;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
            A_address0 = zext_ln43_9_fu_732_p1;
        end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            A_address0 = zext_ln43_7_fu_696_p1;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            A_address0 = zext_ln43_5_fu_660_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            A_address0 = zext_ln43_3_fu_586_p1;
        end else begin
            A_address0 = 'bx;
        end
    end else begin
        A_address0 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        A_ce0 = 1'b1;
    end else begin
        A_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            B_address0 = zext_ln43_23_fu_632_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            B_address0 = zext_ln43_11_fu_554_p1;
        end else begin
            B_address0 = 'bx;
        end
    end else begin
        B_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            B_address1 = zext_ln43_29_fu_651_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            B_address1 = zext_ln43_17_fu_573_p1;
        end else begin
            B_address1 = 'bx;
        end
    end else begin
        B_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        B_ce0 = 1'b1;
    end else begin
        B_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        B_ce1 = 1'b1;
    end else begin
        B_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((icmp_ln37_fu_365_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state2 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state2 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_ii_0_phi_fu_310_p4 = select_ln43_7_reg_954;
    end else begin
        ap_phi_mux_ii_0_phi_fu_310_p4 = ii_0_reg_306;
    end
end

always @ (*) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_indvar_flatten29_phi_fu_277_p4 = add_ln37_reg_926;
    end else begin
        ap_phi_mux_indvar_flatten29_phi_fu_277_p4 = indvar_flatten29_reg_273;
    end
end

always @ (*) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_indvar_flatten_phi_fu_299_p4 = select_ln38_reg_975;
    end else begin
        ap_phi_mux_indvar_flatten_phi_fu_299_p4 = indvar_flatten_reg_295;
    end
end

always @ (*) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_jj_0_phi_fu_321_p4 = jj_reg_1341;
    end else begin
        ap_phi_mux_jj_0_phi_fu_321_p4 = jj_0_reg_317;
    end
end

always @ (*) begin
    if (((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_k_0_phi_fu_288_p4 = select_ln43_2_reg_931;
    end else begin
        ap_phi_mux_k_0_phi_fu_288_p4 = k_0_reg_284;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state36)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        out_r_address0 = out_addr_13_reg_1274;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_r_address0 = out_addr_12_reg_1269;
    end else if (((1'b0 == ap_block_pp0_stage15) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        out_r_address0 = out_addr_10_reg_1239;
    end else if (((1'b0 == ap_block_pp0_stage14) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        out_r_address0 = out_addr_8_reg_1201;
    end else if (((1'b0 == ap_block_pp0_stage13) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        out_r_address0 = out_addr_6_reg_1183;
    end else if (((1'b0 == ap_block_pp0_stage12) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        out_r_address0 = out_addr_4_reg_1150;
    end else if (((1'b0 == ap_block_pp0_stage11) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        out_r_address0 = out_addr_2_reg_1110;
    end else if (((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        out_r_address0 = out_addr_reg_1036;
    end else if (((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        out_r_address0 = zext_ln43_27_fu_815_p1;
    end else if (((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        out_r_address0 = zext_ln43_15_fu_807_p1;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        out_r_address0 = zext_ln43_26_fu_785_p1;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        out_r_address0 = zext_ln43_14_fu_759_p1;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        out_r_address0 = zext_ln43_25_fu_741_p1;
    end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        out_r_address0 = zext_ln43_13_fu_714_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        out_r_address0 = zext_ln43_24_fu_678_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        out_r_address0 = zext_ln43_12_fu_604_p1;
    end else begin
        out_r_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        out_r_address1 = out_addr_15_reg_1296_pp0_iter1_reg;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_r_address1 = out_addr_14_reg_1290_pp0_iter1_reg;
    end else if (((1'b0 == ap_block_pp0_stage15) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        out_r_address1 = out_addr_11_reg_1249;
    end else if (((1'b0 == ap_block_pp0_stage14) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        out_r_address1 = out_addr_9_reg_1206;
    end else if (((1'b0 == ap_block_pp0_stage13) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        out_r_address1 = out_addr_7_reg_1188;
    end else if (((1'b0 == ap_block_pp0_stage12) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        out_r_address1 = out_addr_5_reg_1160;
    end else if (((1'b0 == ap_block_pp0_stage11) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        out_r_address1 = out_addr_3_reg_1123;
    end else if (((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        out_r_address1 = out_addr_1_reg_1049;
    end else if (((1'b0 == ap_block_pp0_stage9) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9))) begin
        out_r_address1 = zext_ln43_33_fu_819_p1;
    end else if (((1'b0 == ap_block_pp0_stage8) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8))) begin
        out_r_address1 = zext_ln43_21_fu_811_p1;
    end else if (((1'b0 == ap_block_pp0_stage7) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        out_r_address1 = zext_ln43_32_fu_798_p1;
    end else if (((1'b0 == ap_block_pp0_stage6) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        out_r_address1 = zext_ln43_20_fu_768_p1;
    end else if (((1'b0 == ap_block_pp0_stage5) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        out_r_address1 = zext_ln43_31_fu_750_p1;
    end else if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        out_r_address1 = zext_ln43_19_fu_723_p1;
    end else if (((1'b0 == ap_block_pp0_stage3) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        out_r_address1 = zext_ln43_30_fu_687_p1;
    end else if (((1'b0 == ap_block_pp0_stage2) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        out_r_address1 = zext_ln43_18_fu_613_p1;
    end else begin
        out_r_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage15_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((1'b0 == ap_block_pp0_stage14_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((1'b0 == ap_block_pp0_stage13_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'b0 == ap_block_pp0_stage11_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9) & (1'b0 == ap_block_pp0_stage9_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10) & (1'b0 == ap_block_pp0_stage10_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_r_ce0 = 1'b1;
    end else begin
        out_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage15_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((1'b0 == ap_block_pp0_stage14_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((1'b0 == ap_block_pp0_stage13_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((1'b0 == ap_block_pp0_stage11_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage9) & (1'b0 == ap_block_pp0_stage9_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7) & (1'b0 == ap_block_pp0_stage7_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage8) & (1'b0 == ap_block_pp0_stage8_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage5) & (1'b0 == ap_block_pp0_stage5_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10) & (1'b0 == ap_block_pp0_stage10_11001)) | ((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6) & (1'b0 == ap_block_pp0_stage6_11001)) | ((1'b1 == ap_CS_fsm_pp0_stage4) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_r_ce1 = 1'b1;
    end else begin
        out_r_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        out_r_d0 = grp_fu_905_p3;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_r_d0 = grp_fu_898_p3;
    end else if (((1'b0 == ap_block_pp0_stage15) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        out_r_d0 = add_ln43_10_reg_1336;
    end else if (((1'b0 == ap_block_pp0_stage14) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        out_r_d0 = add_ln43_8_reg_1326;
    end else if (((1'b0 == ap_block_pp0_stage13) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        out_r_d0 = add_ln43_6_reg_1311;
    end else if (((1'b0 == ap_block_pp0_stage12) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        out_r_d0 = add_ln43_4_reg_1280;
    end else if (((1'b0 == ap_block_pp0_stage11) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        out_r_d0 = add_ln43_2_reg_1211;
    end else if (((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        out_r_d0 = add_ln43_reg_1155;
    end else begin
        out_r_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        out_r_d1 = add_ln43_15_reg_1351;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        out_r_d1 = add_ln43_14_reg_1346;
    end else if (((1'b0 == ap_block_pp0_stage15) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15))) begin
        out_r_d1 = grp_fu_892_p3;
    end else if (((1'b0 == ap_block_pp0_stage14) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14))) begin
        out_r_d1 = add_ln43_9_reg_1331;
    end else if (((1'b0 == ap_block_pp0_stage13) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13))) begin
        out_r_d1 = add_ln43_7_reg_1321;
    end else if (((1'b0 == ap_block_pp0_stage12) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12))) begin
        out_r_d1 = add_ln43_5_reg_1301;
    end else if (((1'b0 == ap_block_pp0_stage11) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11))) begin
        out_r_d1 = add_ln43_3_reg_1259;
    end else if (((1'b0 == ap_block_pp0_stage10) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10))) begin
        out_r_d1 = add_ln43_1_reg_1178;
    end else begin
        out_r_d1 = 'bx;
    end
end

always @ (*) begin
    if ((((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage15_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage14_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage13_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage11_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((icmp_ln37_reg_922 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10) & (1'b0 == ap_block_pp0_stage10_11001)) | ((icmp_ln37_reg_922_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        out_r_we0 = 1'b1;
    end else begin
        out_r_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage15_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage15)) | ((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage14_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage14)) | ((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage13_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage13)) | ((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage12_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage12)) | ((icmp_ln37_reg_922 == 1'd0) & (1'b0 == ap_block_pp0_stage11_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage11)) | ((icmp_ln37_reg_922 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage10) & (1'b0 == ap_block_pp0_stage10_11001)) | ((icmp_ln37_reg_922_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((icmp_ln37_reg_922_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        out_r_we1 = 1'b1;
    end else begin
        out_r_we1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_fu_365_p2 == 1'd1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln37_fu_365_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state36;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((~((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) & (1'b0 == ap_block_pp0_stage1_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
                ap_NS_fsm = ap_ST_fsm_state36;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        ap_ST_fsm_pp0_stage8 : begin
            if ((1'b0 == ap_block_pp0_stage8_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage8;
            end
        end
        ap_ST_fsm_pp0_stage9 : begin
            if ((1'b0 == ap_block_pp0_stage9_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage9;
            end
        end
        ap_ST_fsm_pp0_stage10 : begin
            if ((1'b0 == ap_block_pp0_stage10_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage10;
            end
        end
        ap_ST_fsm_pp0_stage11 : begin
            if ((1'b0 == ap_block_pp0_stage11_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage11;
            end
        end
        ap_ST_fsm_pp0_stage12 : begin
            if ((1'b0 == ap_block_pp0_stage12_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage12;
            end
        end
        ap_ST_fsm_pp0_stage13 : begin
            if ((1'b0 == ap_block_pp0_stage13_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage14;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage13;
            end
        end
        ap_ST_fsm_pp0_stage14 : begin
            if ((1'b0 == ap_block_pp0_stage14_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage15;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage14;
            end
        end
        ap_ST_fsm_pp0_stage15 : begin
            if ((1'b0 == ap_block_pp0_stage15_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage15;
            end
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln37_fu_371_p2 = (ap_phi_mux_indvar_flatten29_phi_fu_277_p4 + 16'd1);

assign add_ln38_1_fu_523_p2 = (ap_phi_mux_indvar_flatten_phi_fu_299_p4 + 10'd1);

assign add_ln43_16_fu_581_p2 = (mul_ln43_17_reg_980 + zext_ln43_fu_578_p1);

assign add_ln43_17_fu_656_p2 = (mul_ln43_18_reg_1027 + zext_ln43_reg_1015);

assign add_ln43_18_fu_692_p2 = (mul_ln43_19_reg_1093 + zext_ln43_reg_1015);

assign add_ln43_19_fu_728_p2 = (mul_ln43_20_reg_1141 + zext_ln43_reg_1015);

assign add_ln43_20_fu_549_p2 = (mul_ln43_16_reg_937 + zext_ln43_10_fu_546_p1);

assign add_ln43_21_fu_600_p2 = (mul_ln43_17_reg_980 + zext_ln43_10_reg_989);

assign add_ln43_22_fu_710_p2 = (mul_ln43_18_reg_1027 + zext_ln43_10_reg_989);

assign add_ln43_23_fu_755_p2 = (mul_ln43_19_reg_1093 + zext_ln43_10_reg_989);

assign add_ln43_24_fu_773_p2 = (mul_ln43_20_reg_1141 + zext_ln43_10_reg_989);

assign add_ln43_25_fu_568_p2 = (mul_ln43_16_reg_937 + zext_ln43_16_fu_564_p1);

assign add_ln43_26_fu_609_p2 = (mul_ln43_17_reg_980 + zext_ln43_16_reg_1002);

assign add_ln43_27_fu_719_p2 = (mul_ln43_18_reg_1027 + zext_ln43_16_reg_1002);

assign add_ln43_28_fu_764_p2 = (mul_ln43_19_reg_1093 + zext_ln43_16_reg_1002);

assign add_ln43_29_fu_777_p2 = (mul_ln43_20_reg_1141 + zext_ln43_16_reg_1002);

assign add_ln43_30_fu_627_p2 = (mul_ln43_16_reg_937 + zext_ln43_22_fu_623_p1);

assign add_ln43_31_fu_674_p2 = (mul_ln43_17_reg_980 + zext_ln43_22_reg_1062);

assign add_ln43_32_fu_737_p2 = (mul_ln43_18_reg_1027 + zext_ln43_22_reg_1062);

assign add_ln43_33_fu_781_p2 = (mul_ln43_19_reg_1093 + zext_ln43_22_reg_1062);

assign add_ln43_34_fu_790_p2 = (mul_ln43_20_reg_1141 + zext_ln43_22_reg_1062);

assign add_ln43_35_fu_646_p2 = (mul_ln43_16_reg_937 + zext_ln43_28_fu_642_p1);

assign add_ln43_36_fu_683_p2 = (mul_ln43_17_reg_980 + zext_ln43_28_reg_1075);

assign add_ln43_37_fu_746_p2 = (mul_ln43_18_reg_1027 + zext_ln43_28_reg_1075);

assign add_ln43_38_fu_794_p2 = (mul_ln43_19_reg_1093 + zext_ln43_28_reg_1075);

assign add_ln43_39_fu_803_p2 = (mul_ln43_20_reg_1141 + zext_ln43_28_reg_1075);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage10 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_pp0_stage11 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_pp0_stage12 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_pp0_stage13 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_pp0_stage14 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_pp0_stage15 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd8];

assign ap_CS_fsm_pp0_stage8 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_pp0_stage9 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd17];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage10_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage11_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage12_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage13 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage13_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage13_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage14 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage14_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage14_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage15 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage15_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage15_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage8_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage9_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage8_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage9_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage10_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage11_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage12_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage13_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage14_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage15_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage4_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage5_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage6_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage7_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage8_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage9_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage10_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage11_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage12_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage13_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage14_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage15_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage5_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage6_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage7_iter0 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign icmp_ln37_fu_365_p2 = ((ap_phi_mux_indvar_flatten29_phi_fu_277_p4 == 16'd62500) ? 1'b1 : 1'b0);

assign icmp_ln38_fu_383_p2 = ((ap_phi_mux_indvar_flatten_phi_fu_299_p4 == 10'd625) ? 1'b1 : 1'b0);

assign icmp_ln39_fu_447_p2 = ((ap_phi_mux_jj_0_phi_fu_321_p4 < 7'd100) ? 1'b1 : 1'b0);

assign ii_fu_459_p2 = (select_ln43_fu_389_p3 + 7'd4);

assign jj_fu_823_p2 = (select_ln43_6_reg_945 + 7'd4);

assign k_fu_377_p2 = (ap_phi_mux_k_0_phi_fu_288_p4 + 7'd1);

assign mul_ln43_16_fu_417_p0 = mul_ln43_16_fu_417_p00;

assign mul_ln43_16_fu_417_p00 = select_ln43_2_fu_405_p3;

assign mul_ln43_16_fu_417_p2 = (mul_ln43_16_fu_417_p0 * $signed('h64));

assign mul_ln43_17_fu_540_p0 = mul_ln43_17_fu_540_p00;

assign mul_ln43_17_fu_540_p00 = select_ln43_7_reg_954;

assign mul_ln43_17_fu_540_p2 = (mul_ln43_17_fu_540_p0 * $signed('h64));

assign mul_ln43_18_fu_594_p0 = mul_ln43_18_fu_594_p00;

assign mul_ln43_18_fu_594_p00 = select_ln43_8_reg_960;

assign mul_ln43_18_fu_594_p2 = (mul_ln43_18_fu_594_p0 * $signed('h64));

assign mul_ln43_19_fu_668_p0 = mul_ln43_19_fu_668_p00;

assign mul_ln43_19_fu_668_p00 = select_ln43_9_reg_965;

assign mul_ln43_19_fu_668_p2 = (mul_ln43_19_fu_668_p0 * $signed('h64));

assign mul_ln43_20_fu_704_p0 = mul_ln43_20_fu_704_p00;

assign mul_ln43_20_fu_704_p00 = select_ln43_10_reg_970;

assign mul_ln43_20_fu_704_p2 = (mul_ln43_20_fu_704_p0 * $signed('h64));

assign or_ln43_1_fu_618_p2 = (select_ln43_6_reg_945 | 7'd2);

assign or_ln43_2_fu_637_p2 = (select_ln43_6_reg_945 | 7'd3);

assign or_ln43_3_fu_347_p2 = (ap_phi_mux_ii_0_phi_fu_310_p4 | 7'd1);

assign or_ln43_4_fu_353_p2 = (ap_phi_mux_ii_0_phi_fu_310_p4 | 7'd2);

assign or_ln43_5_fu_359_p2 = (ap_phi_mux_ii_0_phi_fu_310_p4 | 7'd3);

assign or_ln43_6_fu_453_p2 = (icmp_ln39_fu_447_p2 | icmp_ln38_fu_383_p2);

assign or_ln43_7_fu_481_p2 = (ii_fu_459_p2 | 7'd1);

assign or_ln43_8_fu_495_p2 = (ii_fu_459_p2 | 7'd2);

assign or_ln43_9_fu_509_p2 = (ii_fu_459_p2 | 7'd3);

assign or_ln43_fu_559_p2 = (select_ln43_6_reg_945 | 7'd1);

assign select_ln38_fu_529_p3 = ((icmp_ln38_fu_383_p2[0:0] === 1'b1) ? 10'd1 : add_ln38_1_fu_523_p2);

assign select_ln43_10_fu_515_p3 = ((or_ln43_6_fu_453_p2[0:0] === 1'b1) ? select_ln43_5_fu_439_p3 : or_ln43_9_fu_509_p2);

assign select_ln43_1_fu_397_p3 = ((icmp_ln38_fu_383_p2[0:0] === 1'b1) ? 7'd0 : ap_phi_mux_jj_0_phi_fu_321_p4);

assign select_ln43_2_fu_405_p3 = ((icmp_ln38_fu_383_p2[0:0] === 1'b1) ? k_fu_377_p2 : ap_phi_mux_k_0_phi_fu_288_p4);

assign select_ln43_3_fu_423_p3 = ((icmp_ln38_fu_383_p2[0:0] === 1'b1) ? 7'd1 : or_ln43_3_fu_347_p2);

assign select_ln43_4_fu_431_p3 = ((icmp_ln38_fu_383_p2[0:0] === 1'b1) ? 7'd2 : or_ln43_4_fu_353_p2);

assign select_ln43_5_fu_439_p3 = ((icmp_ln38_fu_383_p2[0:0] === 1'b1) ? 7'd3 : or_ln43_5_fu_359_p2);

assign select_ln43_6_fu_465_p3 = ((or_ln43_6_fu_453_p2[0:0] === 1'b1) ? select_ln43_1_fu_397_p3 : 7'd0);

assign select_ln43_7_fu_473_p3 = ((or_ln43_6_fu_453_p2[0:0] === 1'b1) ? select_ln43_fu_389_p3 : ii_fu_459_p2);

assign select_ln43_8_fu_487_p3 = ((or_ln43_6_fu_453_p2[0:0] === 1'b1) ? select_ln43_3_fu_423_p3 : or_ln43_7_fu_481_p2);

assign select_ln43_9_fu_501_p3 = ((or_ln43_6_fu_453_p2[0:0] === 1'b1) ? select_ln43_4_fu_431_p3 : or_ln43_8_fu_495_p2);

assign select_ln43_fu_389_p3 = ((icmp_ln38_fu_383_p2[0:0] === 1'b1) ? 7'd0 : ap_phi_mux_ii_0_phi_fu_310_p4);

assign zext_ln43_10_fu_546_p1 = select_ln43_6_reg_945;

assign zext_ln43_11_fu_554_p1 = add_ln43_20_fu_549_p2;

assign zext_ln43_12_fu_604_p1 = add_ln43_21_fu_600_p2;

assign zext_ln43_13_fu_714_p1 = add_ln43_22_fu_710_p2;

assign zext_ln43_14_fu_759_p1 = add_ln43_23_fu_755_p2;

assign zext_ln43_15_fu_807_p1 = add_ln43_24_reg_1229;

assign zext_ln43_16_fu_564_p1 = or_ln43_fu_559_p2;

assign zext_ln43_17_fu_573_p1 = add_ln43_25_fu_568_p2;

assign zext_ln43_18_fu_613_p1 = add_ln43_26_fu_609_p2;

assign zext_ln43_19_fu_723_p1 = add_ln43_27_fu_719_p2;

assign zext_ln43_20_fu_768_p1 = add_ln43_28_fu_764_p2;

assign zext_ln43_21_fu_811_p1 = add_ln43_29_reg_1234;

assign zext_ln43_22_fu_623_p1 = or_ln43_1_fu_618_p2;

assign zext_ln43_23_fu_632_p1 = add_ln43_30_fu_627_p2;

assign zext_ln43_24_fu_678_p1 = add_ln43_31_fu_674_p2;

assign zext_ln43_25_fu_741_p1 = add_ln43_32_fu_737_p2;

assign zext_ln43_26_fu_785_p1 = add_ln43_33_fu_781_p2;

assign zext_ln43_27_fu_815_p1 = add_ln43_34_reg_1244;

assign zext_ln43_28_fu_642_p1 = or_ln43_2_fu_637_p2;

assign zext_ln43_29_fu_651_p1 = add_ln43_35_fu_646_p2;

assign zext_ln43_30_fu_687_p1 = add_ln43_36_fu_683_p2;

assign zext_ln43_31_fu_750_p1 = add_ln43_37_fu_746_p2;

assign zext_ln43_32_fu_798_p1 = add_ln43_38_fu_794_p2;

assign zext_ln43_33_fu_819_p1 = add_ln43_39_reg_1254;

assign zext_ln43_3_fu_586_p1 = add_ln43_16_fu_581_p2;

assign zext_ln43_5_fu_660_p1 = add_ln43_17_fu_656_p2;

assign zext_ln43_7_fu_696_p1 = add_ln43_18_fu_692_p2;

assign zext_ln43_9_fu_732_p1 = add_ln43_19_fu_728_p2;

assign zext_ln43_fu_578_p1 = select_ln43_2_reg_931;

always @ (posedge ap_clk) begin
    mul_ln43_16_reg_937[1:0] <= 2'b00;
    select_ln43_8_reg_960[0] <= 1'b1;
    select_ln43_9_reg_965[1] <= 1'b1;
    select_ln43_10_reg_970[1:0] <= 2'b11;
    mul_ln43_17_reg_980[1:0] <= 2'b00;
    zext_ln43_10_reg_989[13:7] <= 7'b0000000;
    zext_ln43_16_reg_1002[0] <= 1'b1;
    zext_ln43_16_reg_1002[13:7] <= 7'b0000000;
    zext_ln43_reg_1015[13:7] <= 7'b0000000;
    mul_ln43_18_reg_1027[1:0] <= 2'b00;
    out_addr_1_reg_1049[0] <= 1'b1;
    zext_ln43_22_reg_1062[1] <= 1'b1;
    zext_ln43_22_reg_1062[13:7] <= 7'b0000000;
    zext_ln43_28_reg_1075[1:0] <= 2'b11;
    zext_ln43_28_reg_1075[13:7] <= 7'b0000000;
    mul_ln43_19_reg_1093[1:0] <= 2'b00;
    out_addr_3_reg_1123[1:0] <= 2'b11;
    mul_ln43_20_reg_1141[1:0] <= 2'b00;
    out_addr_5_reg_1160[0] <= 1'b1;
    out_addr_7_reg_1188[1:0] <= 2'b11;
    out_addr_9_reg_1206[0] <= 1'b1;
    add_ln43_29_reg_1234[0] <= 1'b1;
    out_addr_11_reg_1249[1:0] <= 2'b11;
    add_ln43_39_reg_1254[1:0] <= 2'b11;
    out_addr_13_reg_1274[0] <= 1'b1;
    out_addr_15_reg_1296[1:0] <= 2'b11;
    out_addr_15_reg_1296_pp0_iter1_reg[1:0] <= 2'b11;
end

endmodule //block_mmul
