// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "block_mmul_helper.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic block_mmul_helper::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic block_mmul_helper::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<18> block_mmul_helper::ap_ST_fsm_state1 = "1";
const sc_lv<18> block_mmul_helper::ap_ST_fsm_state2 = "10";
const sc_lv<18> block_mmul_helper::ap_ST_fsm_state3 = "100";
const sc_lv<18> block_mmul_helper::ap_ST_fsm_state4 = "1000";
const sc_lv<18> block_mmul_helper::ap_ST_fsm_state5 = "10000";
const sc_lv<18> block_mmul_helper::ap_ST_fsm_state6 = "100000";
const sc_lv<18> block_mmul_helper::ap_ST_fsm_state7 = "1000000";
const sc_lv<18> block_mmul_helper::ap_ST_fsm_state8 = "10000000";
const sc_lv<18> block_mmul_helper::ap_ST_fsm_state9 = "100000000";
const sc_lv<18> block_mmul_helper::ap_ST_fsm_state10 = "1000000000";
const sc_lv<18> block_mmul_helper::ap_ST_fsm_state11 = "10000000000";
const sc_lv<18> block_mmul_helper::ap_ST_fsm_state12 = "100000000000";
const sc_lv<18> block_mmul_helper::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<18> block_mmul_helper::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<18> block_mmul_helper::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<18> block_mmul_helper::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<18> block_mmul_helper::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<18> block_mmul_helper::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<32> block_mmul_helper::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> block_mmul_helper::ap_const_lv32_2 = "10";
const sc_lv<32> block_mmul_helper::ap_const_lv32_3 = "11";
const sc_lv<1> block_mmul_helper::ap_const_lv1_0 = "0";
const sc_lv<32> block_mmul_helper::ap_const_lv32_4 = "100";
const sc_lv<32> block_mmul_helper::ap_const_lv32_5 = "101";
const sc_lv<32> block_mmul_helper::ap_const_lv32_6 = "110";
const sc_lv<32> block_mmul_helper::ap_const_lv32_7 = "111";
const sc_lv<32> block_mmul_helper::ap_const_lv32_8 = "1000";
const sc_lv<32> block_mmul_helper::ap_const_lv32_1 = "1";
const sc_lv<1> block_mmul_helper::ap_const_lv1_1 = "1";
const sc_lv<32> block_mmul_helper::ap_const_lv32_9 = "1001";
const sc_lv<32> block_mmul_helper::ap_const_lv32_A = "1010";
const sc_lv<32> block_mmul_helper::ap_const_lv32_10 = "10000";
const sc_lv<7> block_mmul_helper::ap_const_lv7_0 = "0000000";
const sc_lv<14> block_mmul_helper::ap_const_lv14_0 = "00000000000000";
const sc_lv<32> block_mmul_helper::ap_const_lv32_B = "1011";
const sc_lv<32> block_mmul_helper::ap_const_lv32_C = "1100";
const sc_lv<32> block_mmul_helper::ap_const_lv32_D = "1101";
const sc_lv<32> block_mmul_helper::ap_const_lv32_E = "1110";
const sc_lv<32> block_mmul_helper::ap_const_lv32_F = "1111";
const sc_lv<16> block_mmul_helper::ap_const_lv16_0 = "0000000000000000";
const sc_lv<7> block_mmul_helper::ap_const_lv7_64 = "1100100";
const sc_lv<14> block_mmul_helper::ap_const_lv14_64 = "1100100";
const sc_lv<7> block_mmul_helper::ap_const_lv7_1 = "1";
const sc_lv<7> block_mmul_helper::ap_const_lv7_2 = "10";
const sc_lv<7> block_mmul_helper::ap_const_lv7_3 = "11";
const sc_lv<32> block_mmul_helper::ap_const_lv32_11 = "10001";
const bool block_mmul_helper::ap_const_boolean_1 = true;

block_mmul_helper::block_mmul_helper(sc_module_name name) : sc_module(name), mVcdFile(0) {
    block_mmul_mac_mubkb_U1 = new block_mmul_mac_mubkb<1,1,16,16,16,16>("block_mmul_mac_mubkb_U1");
    block_mmul_mac_mubkb_U1->din0(select_ln15_reg_1110);
    block_mmul_mac_mubkb_U1->din1(B_load_reg_1118);
    block_mmul_mac_mubkb_U1->din2(grp_fu_294_p3);
    block_mmul_mac_mubkb_U1->dout(grp_fu_785_p3);
    block_mmul_mac_mubkb_U2 = new block_mmul_mac_mubkb<1,1,16,16,16,16>("block_mmul_mac_mubkb_U2");
    block_mmul_mac_mubkb_U2->din0(select_ln15_reg_1110);
    block_mmul_mac_mubkb_U2->din1(select_ln16_reg_1126);
    block_mmul_mac_mubkb_U2->din2(grp_fu_301_p3);
    block_mmul_mac_mubkb_U2->dout(grp_fu_791_p3);
    block_mmul_mac_mubkb_U3 = new block_mmul_mac_mubkb<1,1,16,16,16,16>("block_mmul_mac_mubkb_U3");
    block_mmul_mac_mubkb_U3->din0(select_ln15_reg_1110);
    block_mmul_mac_mubkb_U3->din1(select_ln16_1_reg_1152);
    block_mmul_mac_mubkb_U3->din2(grp_fu_294_p3);
    block_mmul_mac_mubkb_U3->dout(grp_fu_797_p3);
    block_mmul_mac_mubkb_U4 = new block_mmul_mac_mubkb<1,1,16,16,16,16>("block_mmul_mac_mubkb_U4");
    block_mmul_mac_mubkb_U4->din0(select_ln15_reg_1110);
    block_mmul_mac_mubkb_U4->din1(select_ln16_2_reg_1160);
    block_mmul_mac_mubkb_U4->din2(grp_fu_301_p3);
    block_mmul_mac_mubkb_U4->dout(grp_fu_803_p3);
    block_mmul_mac_mubkb_U5 = new block_mmul_mac_mubkb<1,1,16,16,16,16>("block_mmul_mac_mubkb_U5");
    block_mmul_mac_mubkb_U5->din0(select_ln15_1_reg_1134);
    block_mmul_mac_mubkb_U5->din1(B_load_reg_1118);
    block_mmul_mac_mubkb_U5->din2(grp_fu_294_p3);
    block_mmul_mac_mubkb_U5->dout(grp_fu_809_p3);
    block_mmul_mac_mubkb_U6 = new block_mmul_mac_mubkb<1,1,16,16,16,16>("block_mmul_mac_mubkb_U6");
    block_mmul_mac_mubkb_U6->din0(select_ln15_1_reg_1134);
    block_mmul_mac_mubkb_U6->din1(select_ln16_reg_1126);
    block_mmul_mac_mubkb_U6->din2(grp_fu_301_p3);
    block_mmul_mac_mubkb_U6->dout(grp_fu_815_p3);
    block_mmul_mac_mubkb_U7 = new block_mmul_mac_mubkb<1,1,16,16,16,16>("block_mmul_mac_mubkb_U7");
    block_mmul_mac_mubkb_U7->din0(select_ln15_1_reg_1134);
    block_mmul_mac_mubkb_U7->din1(select_ln16_1_reg_1152);
    block_mmul_mac_mubkb_U7->din2(grp_fu_294_p3);
    block_mmul_mac_mubkb_U7->dout(grp_fu_821_p3);
    block_mmul_mac_mubkb_U8 = new block_mmul_mac_mubkb<1,1,16,16,16,16>("block_mmul_mac_mubkb_U8");
    block_mmul_mac_mubkb_U8->din0(select_ln15_1_reg_1134);
    block_mmul_mac_mubkb_U8->din1(select_ln16_2_reg_1160);
    block_mmul_mac_mubkb_U8->din2(grp_fu_301_p3);
    block_mmul_mac_mubkb_U8->dout(grp_fu_827_p3);
    block_mmul_mac_mubkb_U9 = new block_mmul_mac_mubkb<1,1,16,16,16,16>("block_mmul_mac_mubkb_U9");
    block_mmul_mac_mubkb_U9->din0(select_ln15_2_reg_1168);
    block_mmul_mac_mubkb_U9->din1(B_load_reg_1118);
    block_mmul_mac_mubkb_U9->din2(grp_fu_294_p3);
    block_mmul_mac_mubkb_U9->dout(grp_fu_833_p3);
    block_mmul_mac_mubkb_U10 = new block_mmul_mac_mubkb<1,1,16,16,16,16>("block_mmul_mac_mubkb_U10");
    block_mmul_mac_mubkb_U10->din0(select_ln15_2_reg_1168);
    block_mmul_mac_mubkb_U10->din1(select_ln16_reg_1126);
    block_mmul_mac_mubkb_U10->din2(grp_fu_301_p3);
    block_mmul_mac_mubkb_U10->dout(grp_fu_839_p3);
    block_mmul_mac_mubkb_U11 = new block_mmul_mac_mubkb<1,1,16,16,16,16>("block_mmul_mac_mubkb_U11");
    block_mmul_mac_mubkb_U11->din0(select_ln15_2_reg_1168);
    block_mmul_mac_mubkb_U11->din1(select_ln16_1_reg_1152);
    block_mmul_mac_mubkb_U11->din2(grp_fu_294_p3);
    block_mmul_mac_mubkb_U11->dout(grp_fu_845_p3);
    block_mmul_mac_mubkb_U12 = new block_mmul_mac_mubkb<1,1,16,16,16,16>("block_mmul_mac_mubkb_U12");
    block_mmul_mac_mubkb_U12->din0(select_ln15_2_reg_1168);
    block_mmul_mac_mubkb_U12->din1(select_ln16_2_reg_1160);
    block_mmul_mac_mubkb_U12->din2(grp_fu_301_p3);
    block_mmul_mac_mubkb_U12->dout(grp_fu_851_p3);
    block_mmul_mac_mubkb_U13 = new block_mmul_mac_mubkb<1,1,16,16,16,16>("block_mmul_mac_mubkb_U13");
    block_mmul_mac_mubkb_U13->din0(select_ln15_3_reg_1176);
    block_mmul_mac_mubkb_U13->din1(B_load_reg_1118);
    block_mmul_mac_mubkb_U13->din2(grp_fu_294_p3);
    block_mmul_mac_mubkb_U13->dout(grp_fu_857_p3);
    block_mmul_mac_mubkb_U14 = new block_mmul_mac_mubkb<1,1,16,16,16,16>("block_mmul_mac_mubkb_U14");
    block_mmul_mac_mubkb_U14->din0(select_ln15_3_reg_1176);
    block_mmul_mac_mubkb_U14->din1(select_ln16_reg_1126);
    block_mmul_mac_mubkb_U14->din2(grp_fu_301_p3);
    block_mmul_mac_mubkb_U14->dout(grp_fu_863_p3);
    block_mmul_mac_mubkb_U15 = new block_mmul_mac_mubkb<1,1,16,16,16,16>("block_mmul_mac_mubkb_U15");
    block_mmul_mac_mubkb_U15->din0(select_ln15_3_reg_1176);
    block_mmul_mac_mubkb_U15->din1(select_ln16_1_reg_1152);
    block_mmul_mac_mubkb_U15->din2(select_ln14_14_reg_1244);
    block_mmul_mac_mubkb_U15->dout(grp_fu_869_p3);
    block_mmul_mac_mubkb_U16 = new block_mmul_mac_mubkb<1,1,16,16,16,16>("block_mmul_mac_mubkb_U16");
    block_mmul_mac_mubkb_U16->din0(select_ln15_3_reg_1176);
    block_mmul_mac_mubkb_U16->din1(select_ln16_2_reg_1160);
    block_mmul_mac_mubkb_U16->din2(select_ln14_15_reg_1249);
    block_mmul_mac_mubkb_U16->dout(grp_fu_874_p3);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_A_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln15_5_fu_645_p1 );
    sensitive << ( zext_ln15_7_fu_700_p1 );

    SC_METHOD(thread_A_address1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln15_6_fu_655_p1 );
    sensitive << ( zext_ln15_8_fu_704_p1 );

    SC_METHOD(thread_A_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_A_ce1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_B_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln16_fu_675_p1 );
    sensitive << ( zext_ln16_2_fu_708_p1 );

    SC_METHOD(thread_B_address1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( zext_ln16_1_fu_685_p1 );
    sensitive << ( zext_ln16_3_fu_712_p1 );

    SC_METHOD(thread_B_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_B_ce1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_add_ln15_1_fu_486_p2);
    sensitive << ( ii );

    SC_METHOD(thread_add_ln15_2_fu_552_p2);
    sensitive << ( ii );

    SC_METHOD(thread_add_ln15_3_fu_640_p2);
    sensitive << ( mul_ln15_reg_884 );
    sensitive << ( zext_ln15_4_fu_636_p1 );

    SC_METHOD(thread_add_ln15_4_fu_650_p2);
    sensitive << ( mul_ln15_1_reg_949 );
    sensitive << ( zext_ln15_4_fu_636_p1 );

    SC_METHOD(thread_add_ln15_5_fu_660_p2);
    sensitive << ( mul_ln15_2_reg_979 );
    sensitive << ( zext_ln15_4_fu_636_p1 );

    SC_METHOD(thread_add_ln15_6_fu_665_p2);
    sensitive << ( mul_ln15_3_reg_1009 );
    sensitive << ( zext_ln15_4_fu_636_p1 );

    SC_METHOD(thread_add_ln15_fu_420_p2);
    sensitive << ( ii );

    SC_METHOD(thread_add_ln16_1_fu_366_p2);
    sensitive << ( jj );

    SC_METHOD(thread_add_ln16_2_fu_393_p2);
    sensitive << ( jj );

    SC_METHOD(thread_add_ln16_3_fu_670_p2);
    sensitive << ( zext_ln18_reg_889 );
    sensitive << ( phi_mul_reg_274 );

    SC_METHOD(thread_add_ln16_4_fu_680_p2);
    sensitive << ( zext_ln18_2_reg_904 );
    sensitive << ( phi_mul_reg_274 );

    SC_METHOD(thread_add_ln16_5_fu_690_p2);
    sensitive << ( zext_ln18_4_reg_919 );
    sensitive << ( phi_mul_reg_274 );

    SC_METHOD(thread_add_ln16_6_fu_695_p2);
    sensitive << ( zext_ln18_6_reg_934 );
    sensitive << ( phi_mul_reg_274 );

    SC_METHOD(thread_add_ln16_7_fu_779_p2);
    sensitive << ( phi_mul_reg_274 );

    SC_METHOD(thread_add_ln16_fu_339_p2);
    sensitive << ( jj );

    SC_METHOD(thread_add_ln18_10_fu_530_p2);
    sensitive << ( zext_ln18_4_fu_378_p1 );
    sensitive << ( mul_ln15_2_fu_502_p2 );

    SC_METHOD(thread_add_ln18_11_fu_541_p2);
    sensitive << ( zext_ln18_6_fu_405_p1 );
    sensitive << ( mul_ln15_2_fu_502_p2 );

    SC_METHOD(thread_add_ln18_12_fu_574_p2);
    sensitive << ( zext_ln18_fu_324_p1 );
    sensitive << ( mul_ln15_3_fu_568_p2 );

    SC_METHOD(thread_add_ln18_13_fu_585_p2);
    sensitive << ( zext_ln18_2_fu_351_p1 );
    sensitive << ( mul_ln15_3_fu_568_p2 );

    SC_METHOD(thread_add_ln18_14_fu_596_p2);
    sensitive << ( zext_ln18_4_fu_378_p1 );
    sensitive << ( mul_ln15_3_fu_568_p2 );

    SC_METHOD(thread_add_ln18_15_fu_607_p2);
    sensitive << ( zext_ln18_6_fu_405_p1 );
    sensitive << ( mul_ln15_3_fu_568_p2 );

    SC_METHOD(thread_add_ln18_1_fu_355_p2);
    sensitive << ( mul_ln15_fu_318_p2 );
    sensitive << ( zext_ln18_2_fu_351_p1 );

    SC_METHOD(thread_add_ln18_2_fu_382_p2);
    sensitive << ( mul_ln15_fu_318_p2 );
    sensitive << ( zext_ln18_4_fu_378_p1 );

    SC_METHOD(thread_add_ln18_3_fu_409_p2);
    sensitive << ( mul_ln15_fu_318_p2 );
    sensitive << ( zext_ln18_6_fu_405_p1 );

    SC_METHOD(thread_add_ln18_4_fu_442_p2);
    sensitive << ( zext_ln18_fu_324_p1 );
    sensitive << ( mul_ln15_1_fu_436_p2 );

    SC_METHOD(thread_add_ln18_5_fu_453_p2);
    sensitive << ( zext_ln18_2_fu_351_p1 );
    sensitive << ( mul_ln15_1_fu_436_p2 );

    SC_METHOD(thread_add_ln18_6_fu_464_p2);
    sensitive << ( zext_ln18_4_fu_378_p1 );
    sensitive << ( mul_ln15_1_fu_436_p2 );

    SC_METHOD(thread_add_ln18_7_fu_475_p2);
    sensitive << ( zext_ln18_6_fu_405_p1 );
    sensitive << ( mul_ln15_1_fu_436_p2 );

    SC_METHOD(thread_add_ln18_8_fu_508_p2);
    sensitive << ( zext_ln18_fu_324_p1 );
    sensitive << ( mul_ln15_2_fu_502_p2 );

    SC_METHOD(thread_add_ln18_9_fu_519_p2);
    sensitive << ( zext_ln18_2_fu_351_p1 );
    sensitive << ( mul_ln15_2_fu_502_p2 );

    SC_METHOD(thread_add_ln18_fu_328_p2);
    sensitive << ( mul_ln15_fu_318_p2 );
    sensitive << ( zext_ln18_fu_324_p1 );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state15);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state16);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state18 );

    SC_METHOD(thread_grp_fu_294_p3);
    sensitive << ( reg_286 );
    sensitive << ( icmp_ln14_reg_1042 );

    SC_METHOD(thread_grp_fu_301_p3);
    sensitive << ( icmp_ln14_reg_1042 );
    sensitive << ( reg_290 );

    SC_METHOD(thread_icmp_ln10_fu_618_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( k_0_reg_263 );

    SC_METHOD(thread_icmp_ln14_fu_630_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln10_fu_618_p2 );
    sensitive << ( k_0_reg_263 );

    SC_METHOD(thread_icmp_ln15_1_fu_426_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln15_fu_420_p2 );

    SC_METHOD(thread_icmp_ln15_2_fu_492_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln15_1_fu_486_p2 );

    SC_METHOD(thread_icmp_ln15_3_fu_558_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln15_2_fu_552_p2 );

    SC_METHOD(thread_icmp_ln15_fu_308_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ii );

    SC_METHOD(thread_icmp_ln16_1_fu_372_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln16_1_fu_366_p2 );

    SC_METHOD(thread_icmp_ln16_2_fu_399_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln16_2_fu_393_p2 );

    SC_METHOD(thread_icmp_ln16_fu_345_p2);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( add_ln16_fu_339_p2 );

    SC_METHOD(thread_k_fu_624_p2);
    sensitive << ( k_0_reg_263 );

    SC_METHOD(thread_mul_ln15_1_fu_436_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mul_ln15_1_fu_436_p00 );

    SC_METHOD(thread_mul_ln15_1_fu_436_p00);
    sensitive << ( add_ln15_fu_420_p2 );

    SC_METHOD(thread_mul_ln15_1_fu_436_p2);
    sensitive << ( mul_ln15_1_fu_436_p0 );

    SC_METHOD(thread_mul_ln15_2_fu_502_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mul_ln15_2_fu_502_p00 );

    SC_METHOD(thread_mul_ln15_2_fu_502_p00);
    sensitive << ( add_ln15_1_fu_486_p2 );

    SC_METHOD(thread_mul_ln15_2_fu_502_p2);
    sensitive << ( mul_ln15_2_fu_502_p0 );

    SC_METHOD(thread_mul_ln15_3_fu_568_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mul_ln15_3_fu_568_p00 );

    SC_METHOD(thread_mul_ln15_3_fu_568_p00);
    sensitive << ( add_ln15_2_fu_552_p2 );

    SC_METHOD(thread_mul_ln15_3_fu_568_p2);
    sensitive << ( mul_ln15_3_fu_568_p0 );

    SC_METHOD(thread_mul_ln15_fu_318_p0);
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( mul_ln15_fu_318_p00 );

    SC_METHOD(thread_mul_ln15_fu_318_p00);
    sensitive << ( ii );

    SC_METHOD(thread_mul_ln15_fu_318_p2);
    sensitive << ( mul_ln15_fu_318_p0 );

    SC_METHOD(thread_out_r_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( out_addr_reg_894 );
    sensitive << ( out_addr_2_reg_924 );
    sensitive << ( out_addr_4_reg_954 );
    sensitive << ( out_addr_6_reg_964 );
    sensitive << ( out_addr_8_reg_984 );
    sensitive << ( out_addr_10_reg_994 );
    sensitive << ( out_addr_12_reg_1014 );
    sensitive << ( out_addr_14_reg_1024 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_out_r_address1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( out_addr_1_reg_909 );
    sensitive << ( out_addr_3_reg_939 );
    sensitive << ( out_addr_5_reg_959 );
    sensitive << ( out_addr_7_reg_969 );
    sensitive << ( out_addr_9_reg_989 );
    sensitive << ( out_addr_11_reg_999 );
    sensitive << ( out_addr_13_reg_1019 );
    sensitive << ( out_addr_15_reg_1029 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_out_r_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_out_r_ce1);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_out_r_d0);
    sensitive << ( add_ln17_reg_1142 );
    sensitive << ( add_ln17_2_reg_1184 );
    sensitive << ( add_ln17_4_reg_1194 );
    sensitive << ( add_ln17_6_reg_1204 );
    sensitive << ( add_ln17_8_reg_1214 );
    sensitive << ( add_ln17_10_reg_1224 );
    sensitive << ( add_ln17_12_reg_1234 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( add_ln17_14_reg_1254 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_out_r_d1);
    sensitive << ( add_ln17_1_reg_1147 );
    sensitive << ( add_ln17_3_reg_1189 );
    sensitive << ( add_ln17_5_reg_1199 );
    sensitive << ( add_ln17_7_reg_1209 );
    sensitive << ( add_ln17_9_reg_1219 );
    sensitive << ( add_ln17_11_reg_1229 );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( add_ln17_13_reg_1239 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( add_ln17_15_reg_1259 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_out_r_we0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_out_r_we1);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state17 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state15 );
    sensitive << ( ap_CS_fsm_state16 );

    SC_METHOD(thread_select_ln14_14_fu_765_p3);
    sensitive << ( out_r_q0 );
    sensitive << ( icmp_ln14_reg_1042 );

    SC_METHOD(thread_select_ln14_15_fu_772_p3);
    sensitive << ( out_r_q1 );
    sensitive << ( icmp_ln14_reg_1042 );

    SC_METHOD(thread_select_ln15_1_fu_730_p3);
    sensitive << ( A_q1 );
    sensitive << ( icmp_ln15_1_reg_944 );

    SC_METHOD(thread_select_ln15_2_fu_751_p3);
    sensitive << ( A_q0 );
    sensitive << ( icmp_ln15_2_reg_974 );

    SC_METHOD(thread_select_ln15_3_fu_758_p3);
    sensitive << ( A_q1 );
    sensitive << ( icmp_ln15_3_reg_1004 );

    SC_METHOD(thread_select_ln15_fu_716_p3);
    sensitive << ( A_q0 );
    sensitive << ( icmp_ln15_reg_879 );

    SC_METHOD(thread_select_ln16_1_fu_737_p3);
    sensitive << ( B_q0 );
    sensitive << ( icmp_ln16_1_reg_914 );

    SC_METHOD(thread_select_ln16_2_fu_744_p3);
    sensitive << ( B_q1 );
    sensitive << ( icmp_ln16_2_reg_929 );

    SC_METHOD(thread_select_ln16_fu_723_p3);
    sensitive << ( B_q1 );
    sensitive << ( icmp_ln16_reg_899 );

    SC_METHOD(thread_zext_ln15_4_fu_636_p1);
    sensitive << ( k_0_reg_263 );

    SC_METHOD(thread_zext_ln15_5_fu_645_p1);
    sensitive << ( add_ln15_3_fu_640_p2 );

    SC_METHOD(thread_zext_ln15_6_fu_655_p1);
    sensitive << ( add_ln15_4_fu_650_p2 );

    SC_METHOD(thread_zext_ln15_7_fu_700_p1);
    sensitive << ( add_ln15_5_reg_1060 );

    SC_METHOD(thread_zext_ln15_8_fu_704_p1);
    sensitive << ( add_ln15_6_reg_1065 );

    SC_METHOD(thread_zext_ln16_1_fu_685_p1);
    sensitive << ( add_ln16_4_fu_680_p2 );

    SC_METHOD(thread_zext_ln16_2_fu_708_p1);
    sensitive << ( add_ln16_5_reg_1080 );

    SC_METHOD(thread_zext_ln16_3_fu_712_p1);
    sensitive << ( add_ln16_6_reg_1085 );

    SC_METHOD(thread_zext_ln16_fu_675_p1);
    sensitive << ( add_ln16_3_fu_670_p2 );

    SC_METHOD(thread_zext_ln18_10_fu_470_p1);
    sensitive << ( add_ln18_6_fu_464_p2 );

    SC_METHOD(thread_zext_ln18_11_fu_481_p1);
    sensitive << ( add_ln18_7_fu_475_p2 );

    SC_METHOD(thread_zext_ln18_12_fu_514_p1);
    sensitive << ( add_ln18_8_fu_508_p2 );

    SC_METHOD(thread_zext_ln18_13_fu_525_p1);
    sensitive << ( add_ln18_9_fu_519_p2 );

    SC_METHOD(thread_zext_ln18_14_fu_536_p1);
    sensitive << ( add_ln18_10_fu_530_p2 );

    SC_METHOD(thread_zext_ln18_15_fu_547_p1);
    sensitive << ( add_ln18_11_fu_541_p2 );

    SC_METHOD(thread_zext_ln18_16_fu_580_p1);
    sensitive << ( add_ln18_12_fu_574_p2 );

    SC_METHOD(thread_zext_ln18_17_fu_591_p1);
    sensitive << ( add_ln18_13_fu_585_p2 );

    SC_METHOD(thread_zext_ln18_18_fu_602_p1);
    sensitive << ( add_ln18_14_fu_596_p2 );

    SC_METHOD(thread_zext_ln18_19_fu_613_p1);
    sensitive << ( add_ln18_15_fu_607_p2 );

    SC_METHOD(thread_zext_ln18_1_fu_334_p1);
    sensitive << ( add_ln18_fu_328_p2 );

    SC_METHOD(thread_zext_ln18_2_fu_351_p1);
    sensitive << ( add_ln16_fu_339_p2 );

    SC_METHOD(thread_zext_ln18_3_fu_361_p1);
    sensitive << ( add_ln18_1_fu_355_p2 );

    SC_METHOD(thread_zext_ln18_4_fu_378_p1);
    sensitive << ( add_ln16_1_fu_366_p2 );

    SC_METHOD(thread_zext_ln18_5_fu_388_p1);
    sensitive << ( add_ln18_2_fu_382_p2 );

    SC_METHOD(thread_zext_ln18_6_fu_405_p1);
    sensitive << ( add_ln16_2_fu_393_p2 );

    SC_METHOD(thread_zext_ln18_7_fu_415_p1);
    sensitive << ( add_ln18_3_fu_409_p2 );

    SC_METHOD(thread_zext_ln18_8_fu_448_p1);
    sensitive << ( add_ln18_4_fu_442_p2 );

    SC_METHOD(thread_zext_ln18_9_fu_459_p1);
    sensitive << ( add_ln18_5_fu_453_p2 );

    SC_METHOD(thread_zext_ln18_fu_324_p1);
    sensitive << ( jj );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln10_fu_618_p2 );

    ap_CS_fsm = "000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "block_mmul_helper_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, A_address0, "(port)A_address0");
    sc_trace(mVcdFile, A_ce0, "(port)A_ce0");
    sc_trace(mVcdFile, A_q0, "(port)A_q0");
    sc_trace(mVcdFile, A_address1, "(port)A_address1");
    sc_trace(mVcdFile, A_ce1, "(port)A_ce1");
    sc_trace(mVcdFile, A_q1, "(port)A_q1");
    sc_trace(mVcdFile, B_address0, "(port)B_address0");
    sc_trace(mVcdFile, B_ce0, "(port)B_ce0");
    sc_trace(mVcdFile, B_q0, "(port)B_q0");
    sc_trace(mVcdFile, B_address1, "(port)B_address1");
    sc_trace(mVcdFile, B_ce1, "(port)B_ce1");
    sc_trace(mVcdFile, B_q1, "(port)B_q1");
    sc_trace(mVcdFile, out_r_address0, "(port)out_r_address0");
    sc_trace(mVcdFile, out_r_ce0, "(port)out_r_ce0");
    sc_trace(mVcdFile, out_r_we0, "(port)out_r_we0");
    sc_trace(mVcdFile, out_r_d0, "(port)out_r_d0");
    sc_trace(mVcdFile, out_r_q0, "(port)out_r_q0");
    sc_trace(mVcdFile, out_r_address1, "(port)out_r_address1");
    sc_trace(mVcdFile, out_r_ce1, "(port)out_r_ce1");
    sc_trace(mVcdFile, out_r_we1, "(port)out_r_we1");
    sc_trace(mVcdFile, out_r_d1, "(port)out_r_d1");
    sc_trace(mVcdFile, out_r_q1, "(port)out_r_q1");
    sc_trace(mVcdFile, ii, "(port)ii");
    sc_trace(mVcdFile, jj, "(port)jj");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, reg_286, "reg_286");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, icmp_ln14_reg_1042, "icmp_ln14_reg_1042");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, reg_290, "reg_290");
    sc_trace(mVcdFile, icmp_ln15_fu_308_p2, "icmp_ln15_fu_308_p2");
    sc_trace(mVcdFile, icmp_ln15_reg_879, "icmp_ln15_reg_879");
    sc_trace(mVcdFile, mul_ln15_fu_318_p2, "mul_ln15_fu_318_p2");
    sc_trace(mVcdFile, mul_ln15_reg_884, "mul_ln15_reg_884");
    sc_trace(mVcdFile, zext_ln18_fu_324_p1, "zext_ln18_fu_324_p1");
    sc_trace(mVcdFile, zext_ln18_reg_889, "zext_ln18_reg_889");
    sc_trace(mVcdFile, out_addr_reg_894, "out_addr_reg_894");
    sc_trace(mVcdFile, icmp_ln16_fu_345_p2, "icmp_ln16_fu_345_p2");
    sc_trace(mVcdFile, icmp_ln16_reg_899, "icmp_ln16_reg_899");
    sc_trace(mVcdFile, zext_ln18_2_fu_351_p1, "zext_ln18_2_fu_351_p1");
    sc_trace(mVcdFile, zext_ln18_2_reg_904, "zext_ln18_2_reg_904");
    sc_trace(mVcdFile, out_addr_1_reg_909, "out_addr_1_reg_909");
    sc_trace(mVcdFile, icmp_ln16_1_fu_372_p2, "icmp_ln16_1_fu_372_p2");
    sc_trace(mVcdFile, icmp_ln16_1_reg_914, "icmp_ln16_1_reg_914");
    sc_trace(mVcdFile, zext_ln18_4_fu_378_p1, "zext_ln18_4_fu_378_p1");
    sc_trace(mVcdFile, zext_ln18_4_reg_919, "zext_ln18_4_reg_919");
    sc_trace(mVcdFile, out_addr_2_reg_924, "out_addr_2_reg_924");
    sc_trace(mVcdFile, icmp_ln16_2_fu_399_p2, "icmp_ln16_2_fu_399_p2");
    sc_trace(mVcdFile, icmp_ln16_2_reg_929, "icmp_ln16_2_reg_929");
    sc_trace(mVcdFile, zext_ln18_6_fu_405_p1, "zext_ln18_6_fu_405_p1");
    sc_trace(mVcdFile, zext_ln18_6_reg_934, "zext_ln18_6_reg_934");
    sc_trace(mVcdFile, out_addr_3_reg_939, "out_addr_3_reg_939");
    sc_trace(mVcdFile, icmp_ln15_1_fu_426_p2, "icmp_ln15_1_fu_426_p2");
    sc_trace(mVcdFile, icmp_ln15_1_reg_944, "icmp_ln15_1_reg_944");
    sc_trace(mVcdFile, mul_ln15_1_fu_436_p2, "mul_ln15_1_fu_436_p2");
    sc_trace(mVcdFile, mul_ln15_1_reg_949, "mul_ln15_1_reg_949");
    sc_trace(mVcdFile, out_addr_4_reg_954, "out_addr_4_reg_954");
    sc_trace(mVcdFile, out_addr_5_reg_959, "out_addr_5_reg_959");
    sc_trace(mVcdFile, out_addr_6_reg_964, "out_addr_6_reg_964");
    sc_trace(mVcdFile, out_addr_7_reg_969, "out_addr_7_reg_969");
    sc_trace(mVcdFile, icmp_ln15_2_fu_492_p2, "icmp_ln15_2_fu_492_p2");
    sc_trace(mVcdFile, icmp_ln15_2_reg_974, "icmp_ln15_2_reg_974");
    sc_trace(mVcdFile, mul_ln15_2_fu_502_p2, "mul_ln15_2_fu_502_p2");
    sc_trace(mVcdFile, mul_ln15_2_reg_979, "mul_ln15_2_reg_979");
    sc_trace(mVcdFile, out_addr_8_reg_984, "out_addr_8_reg_984");
    sc_trace(mVcdFile, out_addr_9_reg_989, "out_addr_9_reg_989");
    sc_trace(mVcdFile, out_addr_10_reg_994, "out_addr_10_reg_994");
    sc_trace(mVcdFile, out_addr_11_reg_999, "out_addr_11_reg_999");
    sc_trace(mVcdFile, icmp_ln15_3_fu_558_p2, "icmp_ln15_3_fu_558_p2");
    sc_trace(mVcdFile, icmp_ln15_3_reg_1004, "icmp_ln15_3_reg_1004");
    sc_trace(mVcdFile, mul_ln15_3_fu_568_p2, "mul_ln15_3_fu_568_p2");
    sc_trace(mVcdFile, mul_ln15_3_reg_1009, "mul_ln15_3_reg_1009");
    sc_trace(mVcdFile, out_addr_12_reg_1014, "out_addr_12_reg_1014");
    sc_trace(mVcdFile, out_addr_13_reg_1019, "out_addr_13_reg_1019");
    sc_trace(mVcdFile, out_addr_14_reg_1024, "out_addr_14_reg_1024");
    sc_trace(mVcdFile, out_addr_15_reg_1029, "out_addr_15_reg_1029");
    sc_trace(mVcdFile, k_fu_624_p2, "k_fu_624_p2");
    sc_trace(mVcdFile, k_reg_1037, "k_reg_1037");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln14_fu_630_p2, "icmp_ln14_fu_630_p2");
    sc_trace(mVcdFile, icmp_ln10_fu_618_p2, "icmp_ln10_fu_618_p2");
    sc_trace(mVcdFile, add_ln15_5_fu_660_p2, "add_ln15_5_fu_660_p2");
    sc_trace(mVcdFile, add_ln15_5_reg_1060, "add_ln15_5_reg_1060");
    sc_trace(mVcdFile, add_ln15_6_fu_665_p2, "add_ln15_6_fu_665_p2");
    sc_trace(mVcdFile, add_ln15_6_reg_1065, "add_ln15_6_reg_1065");
    sc_trace(mVcdFile, add_ln16_5_fu_690_p2, "add_ln16_5_fu_690_p2");
    sc_trace(mVcdFile, add_ln16_5_reg_1080, "add_ln16_5_reg_1080");
    sc_trace(mVcdFile, add_ln16_6_fu_695_p2, "add_ln16_6_fu_695_p2");
    sc_trace(mVcdFile, add_ln16_6_reg_1085, "add_ln16_6_reg_1085");
    sc_trace(mVcdFile, select_ln15_fu_716_p3, "select_ln15_fu_716_p3");
    sc_trace(mVcdFile, select_ln15_reg_1110, "select_ln15_reg_1110");
    sc_trace(mVcdFile, B_load_reg_1118, "B_load_reg_1118");
    sc_trace(mVcdFile, select_ln16_fu_723_p3, "select_ln16_fu_723_p3");
    sc_trace(mVcdFile, select_ln16_reg_1126, "select_ln16_reg_1126");
    sc_trace(mVcdFile, select_ln15_1_fu_730_p3, "select_ln15_1_fu_730_p3");
    sc_trace(mVcdFile, select_ln15_1_reg_1134, "select_ln15_1_reg_1134");
    sc_trace(mVcdFile, grp_fu_785_p3, "grp_fu_785_p3");
    sc_trace(mVcdFile, add_ln17_reg_1142, "add_ln17_reg_1142");
    sc_trace(mVcdFile, grp_fu_791_p3, "grp_fu_791_p3");
    sc_trace(mVcdFile, add_ln17_1_reg_1147, "add_ln17_1_reg_1147");
    sc_trace(mVcdFile, select_ln16_1_fu_737_p3, "select_ln16_1_fu_737_p3");
    sc_trace(mVcdFile, select_ln16_1_reg_1152, "select_ln16_1_reg_1152");
    sc_trace(mVcdFile, select_ln16_2_fu_744_p3, "select_ln16_2_fu_744_p3");
    sc_trace(mVcdFile, select_ln16_2_reg_1160, "select_ln16_2_reg_1160");
    sc_trace(mVcdFile, select_ln15_2_fu_751_p3, "select_ln15_2_fu_751_p3");
    sc_trace(mVcdFile, select_ln15_2_reg_1168, "select_ln15_2_reg_1168");
    sc_trace(mVcdFile, select_ln15_3_fu_758_p3, "select_ln15_3_fu_758_p3");
    sc_trace(mVcdFile, select_ln15_3_reg_1176, "select_ln15_3_reg_1176");
    sc_trace(mVcdFile, grp_fu_797_p3, "grp_fu_797_p3");
    sc_trace(mVcdFile, add_ln17_2_reg_1184, "add_ln17_2_reg_1184");
    sc_trace(mVcdFile, grp_fu_803_p3, "grp_fu_803_p3");
    sc_trace(mVcdFile, add_ln17_3_reg_1189, "add_ln17_3_reg_1189");
    sc_trace(mVcdFile, grp_fu_809_p3, "grp_fu_809_p3");
    sc_trace(mVcdFile, add_ln17_4_reg_1194, "add_ln17_4_reg_1194");
    sc_trace(mVcdFile, grp_fu_815_p3, "grp_fu_815_p3");
    sc_trace(mVcdFile, add_ln17_5_reg_1199, "add_ln17_5_reg_1199");
    sc_trace(mVcdFile, grp_fu_821_p3, "grp_fu_821_p3");
    sc_trace(mVcdFile, add_ln17_6_reg_1204, "add_ln17_6_reg_1204");
    sc_trace(mVcdFile, grp_fu_827_p3, "grp_fu_827_p3");
    sc_trace(mVcdFile, add_ln17_7_reg_1209, "add_ln17_7_reg_1209");
    sc_trace(mVcdFile, grp_fu_833_p3, "grp_fu_833_p3");
    sc_trace(mVcdFile, add_ln17_8_reg_1214, "add_ln17_8_reg_1214");
    sc_trace(mVcdFile, grp_fu_839_p3, "grp_fu_839_p3");
    sc_trace(mVcdFile, add_ln17_9_reg_1219, "add_ln17_9_reg_1219");
    sc_trace(mVcdFile, grp_fu_845_p3, "grp_fu_845_p3");
    sc_trace(mVcdFile, add_ln17_10_reg_1224, "add_ln17_10_reg_1224");
    sc_trace(mVcdFile, grp_fu_851_p3, "grp_fu_851_p3");
    sc_trace(mVcdFile, add_ln17_11_reg_1229, "add_ln17_11_reg_1229");
    sc_trace(mVcdFile, grp_fu_857_p3, "grp_fu_857_p3");
    sc_trace(mVcdFile, add_ln17_12_reg_1234, "add_ln17_12_reg_1234");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, grp_fu_863_p3, "grp_fu_863_p3");
    sc_trace(mVcdFile, add_ln17_13_reg_1239, "add_ln17_13_reg_1239");
    sc_trace(mVcdFile, select_ln14_14_fu_765_p3, "select_ln14_14_fu_765_p3");
    sc_trace(mVcdFile, select_ln14_14_reg_1244, "select_ln14_14_reg_1244");
    sc_trace(mVcdFile, select_ln14_15_fu_772_p3, "select_ln14_15_fu_772_p3");
    sc_trace(mVcdFile, select_ln14_15_reg_1249, "select_ln14_15_reg_1249");
    sc_trace(mVcdFile, grp_fu_869_p3, "grp_fu_869_p3");
    sc_trace(mVcdFile, add_ln17_14_reg_1254, "add_ln17_14_reg_1254");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, grp_fu_874_p3, "grp_fu_874_p3");
    sc_trace(mVcdFile, add_ln17_15_reg_1259, "add_ln17_15_reg_1259");
    sc_trace(mVcdFile, add_ln16_7_fu_779_p2, "add_ln16_7_fu_779_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, k_0_reg_263, "k_0_reg_263");
    sc_trace(mVcdFile, phi_mul_reg_274, "phi_mul_reg_274");
    sc_trace(mVcdFile, zext_ln18_1_fu_334_p1, "zext_ln18_1_fu_334_p1");
    sc_trace(mVcdFile, zext_ln18_3_fu_361_p1, "zext_ln18_3_fu_361_p1");
    sc_trace(mVcdFile, zext_ln18_5_fu_388_p1, "zext_ln18_5_fu_388_p1");
    sc_trace(mVcdFile, zext_ln18_7_fu_415_p1, "zext_ln18_7_fu_415_p1");
    sc_trace(mVcdFile, zext_ln18_8_fu_448_p1, "zext_ln18_8_fu_448_p1");
    sc_trace(mVcdFile, zext_ln18_9_fu_459_p1, "zext_ln18_9_fu_459_p1");
    sc_trace(mVcdFile, zext_ln18_10_fu_470_p1, "zext_ln18_10_fu_470_p1");
    sc_trace(mVcdFile, zext_ln18_11_fu_481_p1, "zext_ln18_11_fu_481_p1");
    sc_trace(mVcdFile, zext_ln18_12_fu_514_p1, "zext_ln18_12_fu_514_p1");
    sc_trace(mVcdFile, zext_ln18_13_fu_525_p1, "zext_ln18_13_fu_525_p1");
    sc_trace(mVcdFile, zext_ln18_14_fu_536_p1, "zext_ln18_14_fu_536_p1");
    sc_trace(mVcdFile, zext_ln18_15_fu_547_p1, "zext_ln18_15_fu_547_p1");
    sc_trace(mVcdFile, zext_ln18_16_fu_580_p1, "zext_ln18_16_fu_580_p1");
    sc_trace(mVcdFile, zext_ln18_17_fu_591_p1, "zext_ln18_17_fu_591_p1");
    sc_trace(mVcdFile, zext_ln18_18_fu_602_p1, "zext_ln18_18_fu_602_p1");
    sc_trace(mVcdFile, zext_ln18_19_fu_613_p1, "zext_ln18_19_fu_613_p1");
    sc_trace(mVcdFile, zext_ln15_5_fu_645_p1, "zext_ln15_5_fu_645_p1");
    sc_trace(mVcdFile, zext_ln15_6_fu_655_p1, "zext_ln15_6_fu_655_p1");
    sc_trace(mVcdFile, zext_ln16_fu_675_p1, "zext_ln16_fu_675_p1");
    sc_trace(mVcdFile, zext_ln16_1_fu_685_p1, "zext_ln16_1_fu_685_p1");
    sc_trace(mVcdFile, zext_ln15_7_fu_700_p1, "zext_ln15_7_fu_700_p1");
    sc_trace(mVcdFile, zext_ln15_8_fu_704_p1, "zext_ln15_8_fu_704_p1");
    sc_trace(mVcdFile, zext_ln16_2_fu_708_p1, "zext_ln16_2_fu_708_p1");
    sc_trace(mVcdFile, zext_ln16_3_fu_712_p1, "zext_ln16_3_fu_712_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, ap_CS_fsm_state15, "ap_CS_fsm_state15");
    sc_trace(mVcdFile, ap_CS_fsm_state16, "ap_CS_fsm_state16");
    sc_trace(mVcdFile, mul_ln15_fu_318_p0, "mul_ln15_fu_318_p0");
    sc_trace(mVcdFile, add_ln18_fu_328_p2, "add_ln18_fu_328_p2");
    sc_trace(mVcdFile, add_ln16_fu_339_p2, "add_ln16_fu_339_p2");
    sc_trace(mVcdFile, add_ln18_1_fu_355_p2, "add_ln18_1_fu_355_p2");
    sc_trace(mVcdFile, add_ln16_1_fu_366_p2, "add_ln16_1_fu_366_p2");
    sc_trace(mVcdFile, add_ln18_2_fu_382_p2, "add_ln18_2_fu_382_p2");
    sc_trace(mVcdFile, add_ln16_2_fu_393_p2, "add_ln16_2_fu_393_p2");
    sc_trace(mVcdFile, add_ln18_3_fu_409_p2, "add_ln18_3_fu_409_p2");
    sc_trace(mVcdFile, add_ln15_fu_420_p2, "add_ln15_fu_420_p2");
    sc_trace(mVcdFile, mul_ln15_1_fu_436_p0, "mul_ln15_1_fu_436_p0");
    sc_trace(mVcdFile, add_ln18_4_fu_442_p2, "add_ln18_4_fu_442_p2");
    sc_trace(mVcdFile, add_ln18_5_fu_453_p2, "add_ln18_5_fu_453_p2");
    sc_trace(mVcdFile, add_ln18_6_fu_464_p2, "add_ln18_6_fu_464_p2");
    sc_trace(mVcdFile, add_ln18_7_fu_475_p2, "add_ln18_7_fu_475_p2");
    sc_trace(mVcdFile, add_ln15_1_fu_486_p2, "add_ln15_1_fu_486_p2");
    sc_trace(mVcdFile, mul_ln15_2_fu_502_p0, "mul_ln15_2_fu_502_p0");
    sc_trace(mVcdFile, add_ln18_8_fu_508_p2, "add_ln18_8_fu_508_p2");
    sc_trace(mVcdFile, add_ln18_9_fu_519_p2, "add_ln18_9_fu_519_p2");
    sc_trace(mVcdFile, add_ln18_10_fu_530_p2, "add_ln18_10_fu_530_p2");
    sc_trace(mVcdFile, add_ln18_11_fu_541_p2, "add_ln18_11_fu_541_p2");
    sc_trace(mVcdFile, add_ln15_2_fu_552_p2, "add_ln15_2_fu_552_p2");
    sc_trace(mVcdFile, mul_ln15_3_fu_568_p0, "mul_ln15_3_fu_568_p0");
    sc_trace(mVcdFile, add_ln18_12_fu_574_p2, "add_ln18_12_fu_574_p2");
    sc_trace(mVcdFile, add_ln18_13_fu_585_p2, "add_ln18_13_fu_585_p2");
    sc_trace(mVcdFile, add_ln18_14_fu_596_p2, "add_ln18_14_fu_596_p2");
    sc_trace(mVcdFile, add_ln18_15_fu_607_p2, "add_ln18_15_fu_607_p2");
    sc_trace(mVcdFile, zext_ln15_4_fu_636_p1, "zext_ln15_4_fu_636_p1");
    sc_trace(mVcdFile, add_ln15_3_fu_640_p2, "add_ln15_3_fu_640_p2");
    sc_trace(mVcdFile, add_ln15_4_fu_650_p2, "add_ln15_4_fu_650_p2");
    sc_trace(mVcdFile, add_ln16_3_fu_670_p2, "add_ln16_3_fu_670_p2");
    sc_trace(mVcdFile, add_ln16_4_fu_680_p2, "add_ln16_4_fu_680_p2");
    sc_trace(mVcdFile, grp_fu_294_p3, "grp_fu_294_p3");
    sc_trace(mVcdFile, grp_fu_301_p3, "grp_fu_301_p3");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, mul_ln15_1_fu_436_p00, "mul_ln15_1_fu_436_p00");
    sc_trace(mVcdFile, mul_ln15_2_fu_502_p00, "mul_ln15_2_fu_502_p00");
    sc_trace(mVcdFile, mul_ln15_3_fu_568_p00, "mul_ln15_3_fu_568_p00");
    sc_trace(mVcdFile, mul_ln15_fu_318_p00, "mul_ln15_fu_318_p00");
#endif

    }
}

block_mmul_helper::~block_mmul_helper() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete block_mmul_mac_mubkb_U1;
    delete block_mmul_mac_mubkb_U2;
    delete block_mmul_mac_mubkb_U3;
    delete block_mmul_mac_mubkb_U4;
    delete block_mmul_mac_mubkb_U5;
    delete block_mmul_mac_mubkb_U6;
    delete block_mmul_mac_mubkb_U7;
    delete block_mmul_mac_mubkb_U8;
    delete block_mmul_mac_mubkb_U9;
    delete block_mmul_mac_mubkb_U10;
    delete block_mmul_mac_mubkb_U11;
    delete block_mmul_mac_mubkb_U12;
    delete block_mmul_mac_mubkb_U13;
    delete block_mmul_mac_mubkb_U14;
    delete block_mmul_mac_mubkb_U15;
    delete block_mmul_mac_mubkb_U16;
}

void block_mmul_helper::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        k_0_reg_263 = k_reg_1037.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        k_0_reg_263 = ap_const_lv7_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        phi_mul_reg_274 = add_ln16_7_fu_779_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        phi_mul_reg_274 = ap_const_lv14_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        B_load_reg_1118 = B_q0.read();
        select_ln15_1_reg_1134 = select_ln15_1_fu_730_p3.read();
        select_ln15_reg_1110 = select_ln15_fu_716_p3.read();
        select_ln16_reg_1126 = select_ln16_fu_723_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln10_fu_618_p2.read()) && esl_seteq<1,1,1>(icmp_ln15_2_reg_974.read(), ap_const_lv1_1))) {
        add_ln15_5_reg_1060 = add_ln15_5_fu_660_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln10_fu_618_p2.read()) && esl_seteq<1,1,1>(icmp_ln15_3_reg_1004.read(), ap_const_lv1_1))) {
        add_ln15_6_reg_1065 = add_ln15_6_fu_665_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln10_fu_618_p2.read()) && esl_seteq<1,1,1>(icmp_ln16_1_reg_914.read(), ap_const_lv1_1))) {
        add_ln16_5_reg_1080 = add_ln16_5_fu_690_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln10_fu_618_p2.read()) && esl_seteq<1,1,1>(icmp_ln16_2_reg_929.read(), ap_const_lv1_1))) {
        add_ln16_6_reg_1085 = add_ln16_6_fu_695_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        add_ln17_10_reg_1224 = grp_fu_845_p3.read();
        add_ln17_11_reg_1229 = grp_fu_851_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        add_ln17_12_reg_1234 = grp_fu_857_p3.read();
        add_ln17_13_reg_1239 = grp_fu_863_p3.read();
        select_ln14_14_reg_1244 = select_ln14_14_fu_765_p3.read();
        select_ln14_15_reg_1249 = select_ln14_15_fu_772_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        add_ln17_14_reg_1254 = grp_fu_869_p3.read();
        add_ln17_15_reg_1259 = grp_fu_874_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        add_ln17_1_reg_1147 = grp_fu_791_p3.read();
        add_ln17_reg_1142 = grp_fu_785_p3.read();
        select_ln15_2_reg_1168 = select_ln15_2_fu_751_p3.read();
        select_ln15_3_reg_1176 = select_ln15_3_fu_758_p3.read();
        select_ln16_1_reg_1152 = select_ln16_1_fu_737_p3.read();
        select_ln16_2_reg_1160 = select_ln16_2_fu_744_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        add_ln17_2_reg_1184 = grp_fu_797_p3.read();
        add_ln17_3_reg_1189 = grp_fu_803_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        add_ln17_4_reg_1194 = grp_fu_809_p3.read();
        add_ln17_5_reg_1199 = grp_fu_815_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        add_ln17_6_reg_1204 = grp_fu_821_p3.read();
        add_ln17_7_reg_1209 = grp_fu_827_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        add_ln17_8_reg_1214 = grp_fu_833_p3.read();
        add_ln17_9_reg_1219 = grp_fu_839_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln10_fu_618_p2.read()))) {
        icmp_ln14_reg_1042 = icmp_ln14_fu_630_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        icmp_ln15_1_reg_944 = icmp_ln15_1_fu_426_p2.read();
        icmp_ln15_2_reg_974 = icmp_ln15_2_fu_492_p2.read();
        icmp_ln15_3_reg_1004 = icmp_ln15_3_fu_558_p2.read();
        icmp_ln15_reg_879 = icmp_ln15_fu_308_p2.read();
        icmp_ln16_1_reg_914 = icmp_ln16_1_fu_372_p2.read();
        icmp_ln16_2_reg_929 = icmp_ln16_2_fu_399_p2.read();
        icmp_ln16_reg_899 = icmp_ln16_fu_345_p2.read();
        mul_ln15_1_reg_949 = mul_ln15_1_fu_436_p2.read();
        mul_ln15_2_reg_979 = mul_ln15_2_fu_502_p2.read();
        mul_ln15_3_reg_1009 = mul_ln15_3_fu_568_p2.read();
        mul_ln15_reg_884 = mul_ln15_fu_318_p2.read();
        out_addr_10_reg_994 =  (sc_lv<14>) (zext_ln18_14_fu_536_p1.read());
        out_addr_11_reg_999 =  (sc_lv<14>) (zext_ln18_15_fu_547_p1.read());
        out_addr_12_reg_1014 =  (sc_lv<14>) (zext_ln18_16_fu_580_p1.read());
        out_addr_13_reg_1019 =  (sc_lv<14>) (zext_ln18_17_fu_591_p1.read());
        out_addr_14_reg_1024 =  (sc_lv<14>) (zext_ln18_18_fu_602_p1.read());
        out_addr_15_reg_1029 =  (sc_lv<14>) (zext_ln18_19_fu_613_p1.read());
        out_addr_1_reg_909 =  (sc_lv<14>) (zext_ln18_3_fu_361_p1.read());
        out_addr_2_reg_924 =  (sc_lv<14>) (zext_ln18_5_fu_388_p1.read());
        out_addr_3_reg_939 =  (sc_lv<14>) (zext_ln18_7_fu_415_p1.read());
        out_addr_4_reg_954 =  (sc_lv<14>) (zext_ln18_8_fu_448_p1.read());
        out_addr_5_reg_959 =  (sc_lv<14>) (zext_ln18_9_fu_459_p1.read());
        out_addr_6_reg_964 =  (sc_lv<14>) (zext_ln18_10_fu_470_p1.read());
        out_addr_7_reg_969 =  (sc_lv<14>) (zext_ln18_11_fu_481_p1.read());
        out_addr_8_reg_984 =  (sc_lv<14>) (zext_ln18_12_fu_514_p1.read());
        out_addr_9_reg_989 =  (sc_lv<14>) (zext_ln18_13_fu_525_p1.read());
        out_addr_reg_894 =  (sc_lv<14>) (zext_ln18_1_fu_334_p1.read());
        zext_ln18_2_reg_904 = zext_ln18_2_fu_351_p1.read();
        zext_ln18_4_reg_919 = zext_ln18_4_fu_378_p1.read();
        zext_ln18_6_reg_934 = zext_ln18_6_fu_405_p1.read();
        zext_ln18_reg_889 = zext_ln18_fu_324_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        k_reg_1037 = k_fu_624_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
  esl_seteq<1,1,1>(icmp_ln14_reg_1042.read(), ap_const_lv1_0)) || (esl_seteq<1,1,1>(icmp_ln14_reg_1042.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) || (esl_seteq<1,1,1>(icmp_ln14_reg_1042.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) || (esl_seteq<1,1,1>(icmp_ln14_reg_1042.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) || (esl_seteq<1,1,1>(icmp_ln14_reg_1042.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) || (esl_seteq<1,1,1>(icmp_ln14_reg_1042.read(), ap_const_lv1_0) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())))) {
        reg_286 = out_r_q0.read();
        reg_290 = out_r_q1.read();
    }
}

void block_mmul_helper::thread_A_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        A_address0 =  (sc_lv<14>) (zext_ln15_7_fu_700_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        A_address0 =  (sc_lv<14>) (zext_ln15_5_fu_645_p1.read());
    } else {
        A_address0 = "XXXXXXXXXXXXXX";
    }
}

void block_mmul_helper::thread_A_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        A_address1 =  (sc_lv<14>) (zext_ln15_8_fu_704_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        A_address1 =  (sc_lv<14>) (zext_ln15_6_fu_655_p1.read());
    } else {
        A_address1 = "XXXXXXXXXXXXXX";
    }
}

void block_mmul_helper::thread_A_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        A_ce0 = ap_const_logic_1;
    } else {
        A_ce0 = ap_const_logic_0;
    }
}

void block_mmul_helper::thread_A_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        A_ce1 = ap_const_logic_1;
    } else {
        A_ce1 = ap_const_logic_0;
    }
}

void block_mmul_helper::thread_B_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        B_address0 =  (sc_lv<14>) (zext_ln16_2_fu_708_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        B_address0 =  (sc_lv<14>) (zext_ln16_fu_675_p1.read());
    } else {
        B_address0 = "XXXXXXXXXXXXXX";
    }
}

void block_mmul_helper::thread_B_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        B_address1 =  (sc_lv<14>) (zext_ln16_3_fu_712_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        B_address1 =  (sc_lv<14>) (zext_ln16_1_fu_685_p1.read());
    } else {
        B_address1 = "XXXXXXXXXXXXXX";
    }
}

void block_mmul_helper::thread_B_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        B_ce0 = ap_const_logic_1;
    } else {
        B_ce0 = ap_const_logic_0;
    }
}

void block_mmul_helper::thread_B_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()))) {
        B_ce1 = ap_const_logic_1;
    } else {
        B_ce1 = ap_const_logic_0;
    }
}

void block_mmul_helper::thread_add_ln15_1_fu_486_p2() {
    add_ln15_1_fu_486_p2 = (!ii.read().is_01() || !ap_const_lv7_2.is_01())? sc_lv<7>(): (sc_biguint<7>(ii.read()) + sc_biguint<7>(ap_const_lv7_2));
}

void block_mmul_helper::thread_add_ln15_2_fu_552_p2() {
    add_ln15_2_fu_552_p2 = (!ii.read().is_01() || !ap_const_lv7_3.is_01())? sc_lv<7>(): (sc_biguint<7>(ii.read()) + sc_biguint<7>(ap_const_lv7_3));
}

void block_mmul_helper::thread_add_ln15_3_fu_640_p2() {
    add_ln15_3_fu_640_p2 = (!mul_ln15_reg_884.read().is_01() || !zext_ln15_4_fu_636_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(mul_ln15_reg_884.read()) + sc_biguint<14>(zext_ln15_4_fu_636_p1.read()));
}

void block_mmul_helper::thread_add_ln15_4_fu_650_p2() {
    add_ln15_4_fu_650_p2 = (!mul_ln15_1_reg_949.read().is_01() || !zext_ln15_4_fu_636_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(mul_ln15_1_reg_949.read()) + sc_biguint<14>(zext_ln15_4_fu_636_p1.read()));
}

void block_mmul_helper::thread_add_ln15_5_fu_660_p2() {
    add_ln15_5_fu_660_p2 = (!mul_ln15_2_reg_979.read().is_01() || !zext_ln15_4_fu_636_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(mul_ln15_2_reg_979.read()) + sc_biguint<14>(zext_ln15_4_fu_636_p1.read()));
}

void block_mmul_helper::thread_add_ln15_6_fu_665_p2() {
    add_ln15_6_fu_665_p2 = (!mul_ln15_3_reg_1009.read().is_01() || !zext_ln15_4_fu_636_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(mul_ln15_3_reg_1009.read()) + sc_biguint<14>(zext_ln15_4_fu_636_p1.read()));
}

void block_mmul_helper::thread_add_ln15_fu_420_p2() {
    add_ln15_fu_420_p2 = (!ii.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(ii.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void block_mmul_helper::thread_add_ln16_1_fu_366_p2() {
    add_ln16_1_fu_366_p2 = (!jj.read().is_01() || !ap_const_lv7_2.is_01())? sc_lv<7>(): (sc_biguint<7>(jj.read()) + sc_biguint<7>(ap_const_lv7_2));
}

void block_mmul_helper::thread_add_ln16_2_fu_393_p2() {
    add_ln16_2_fu_393_p2 = (!jj.read().is_01() || !ap_const_lv7_3.is_01())? sc_lv<7>(): (sc_biguint<7>(jj.read()) + sc_biguint<7>(ap_const_lv7_3));
}

void block_mmul_helper::thread_add_ln16_3_fu_670_p2() {
    add_ln16_3_fu_670_p2 = (!phi_mul_reg_274.read().is_01() || !zext_ln18_reg_889.read().is_01())? sc_lv<14>(): (sc_biguint<14>(phi_mul_reg_274.read()) + sc_biguint<14>(zext_ln18_reg_889.read()));
}

void block_mmul_helper::thread_add_ln16_4_fu_680_p2() {
    add_ln16_4_fu_680_p2 = (!phi_mul_reg_274.read().is_01() || !zext_ln18_2_reg_904.read().is_01())? sc_lv<14>(): (sc_biguint<14>(phi_mul_reg_274.read()) + sc_biguint<14>(zext_ln18_2_reg_904.read()));
}

void block_mmul_helper::thread_add_ln16_5_fu_690_p2() {
    add_ln16_5_fu_690_p2 = (!phi_mul_reg_274.read().is_01() || !zext_ln18_4_reg_919.read().is_01())? sc_lv<14>(): (sc_biguint<14>(phi_mul_reg_274.read()) + sc_biguint<14>(zext_ln18_4_reg_919.read()));
}

void block_mmul_helper::thread_add_ln16_6_fu_695_p2() {
    add_ln16_6_fu_695_p2 = (!phi_mul_reg_274.read().is_01() || !zext_ln18_6_reg_934.read().is_01())? sc_lv<14>(): (sc_biguint<14>(phi_mul_reg_274.read()) + sc_biguint<14>(zext_ln18_6_reg_934.read()));
}

void block_mmul_helper::thread_add_ln16_7_fu_779_p2() {
    add_ln16_7_fu_779_p2 = (!phi_mul_reg_274.read().is_01() || !ap_const_lv14_64.is_01())? sc_lv<14>(): (sc_biguint<14>(phi_mul_reg_274.read()) + sc_biguint<14>(ap_const_lv14_64));
}

void block_mmul_helper::thread_add_ln16_fu_339_p2() {
    add_ln16_fu_339_p2 = (!jj.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(jj.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void block_mmul_helper::thread_add_ln18_10_fu_530_p2() {
    add_ln18_10_fu_530_p2 = (!mul_ln15_2_fu_502_p2.read().is_01() || !zext_ln18_4_fu_378_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(mul_ln15_2_fu_502_p2.read()) + sc_biguint<14>(zext_ln18_4_fu_378_p1.read()));
}

void block_mmul_helper::thread_add_ln18_11_fu_541_p2() {
    add_ln18_11_fu_541_p2 = (!mul_ln15_2_fu_502_p2.read().is_01() || !zext_ln18_6_fu_405_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(mul_ln15_2_fu_502_p2.read()) + sc_biguint<14>(zext_ln18_6_fu_405_p1.read()));
}

void block_mmul_helper::thread_add_ln18_12_fu_574_p2() {
    add_ln18_12_fu_574_p2 = (!mul_ln15_3_fu_568_p2.read().is_01() || !zext_ln18_fu_324_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(mul_ln15_3_fu_568_p2.read()) + sc_biguint<14>(zext_ln18_fu_324_p1.read()));
}

void block_mmul_helper::thread_add_ln18_13_fu_585_p2() {
    add_ln18_13_fu_585_p2 = (!mul_ln15_3_fu_568_p2.read().is_01() || !zext_ln18_2_fu_351_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(mul_ln15_3_fu_568_p2.read()) + sc_biguint<14>(zext_ln18_2_fu_351_p1.read()));
}

void block_mmul_helper::thread_add_ln18_14_fu_596_p2() {
    add_ln18_14_fu_596_p2 = (!mul_ln15_3_fu_568_p2.read().is_01() || !zext_ln18_4_fu_378_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(mul_ln15_3_fu_568_p2.read()) + sc_biguint<14>(zext_ln18_4_fu_378_p1.read()));
}

void block_mmul_helper::thread_add_ln18_15_fu_607_p2() {
    add_ln18_15_fu_607_p2 = (!mul_ln15_3_fu_568_p2.read().is_01() || !zext_ln18_6_fu_405_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(mul_ln15_3_fu_568_p2.read()) + sc_biguint<14>(zext_ln18_6_fu_405_p1.read()));
}

void block_mmul_helper::thread_add_ln18_1_fu_355_p2() {
    add_ln18_1_fu_355_p2 = (!mul_ln15_fu_318_p2.read().is_01() || !zext_ln18_2_fu_351_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(mul_ln15_fu_318_p2.read()) + sc_biguint<14>(zext_ln18_2_fu_351_p1.read()));
}

void block_mmul_helper::thread_add_ln18_2_fu_382_p2() {
    add_ln18_2_fu_382_p2 = (!mul_ln15_fu_318_p2.read().is_01() || !zext_ln18_4_fu_378_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(mul_ln15_fu_318_p2.read()) + sc_biguint<14>(zext_ln18_4_fu_378_p1.read()));
}

void block_mmul_helper::thread_add_ln18_3_fu_409_p2() {
    add_ln18_3_fu_409_p2 = (!mul_ln15_fu_318_p2.read().is_01() || !zext_ln18_6_fu_405_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(mul_ln15_fu_318_p2.read()) + sc_biguint<14>(zext_ln18_6_fu_405_p1.read()));
}

void block_mmul_helper::thread_add_ln18_4_fu_442_p2() {
    add_ln18_4_fu_442_p2 = (!mul_ln15_1_fu_436_p2.read().is_01() || !zext_ln18_fu_324_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(mul_ln15_1_fu_436_p2.read()) + sc_biguint<14>(zext_ln18_fu_324_p1.read()));
}

void block_mmul_helper::thread_add_ln18_5_fu_453_p2() {
    add_ln18_5_fu_453_p2 = (!mul_ln15_1_fu_436_p2.read().is_01() || !zext_ln18_2_fu_351_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(mul_ln15_1_fu_436_p2.read()) + sc_biguint<14>(zext_ln18_2_fu_351_p1.read()));
}

void block_mmul_helper::thread_add_ln18_6_fu_464_p2() {
    add_ln18_6_fu_464_p2 = (!mul_ln15_1_fu_436_p2.read().is_01() || !zext_ln18_4_fu_378_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(mul_ln15_1_fu_436_p2.read()) + sc_biguint<14>(zext_ln18_4_fu_378_p1.read()));
}

void block_mmul_helper::thread_add_ln18_7_fu_475_p2() {
    add_ln18_7_fu_475_p2 = (!mul_ln15_1_fu_436_p2.read().is_01() || !zext_ln18_6_fu_405_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(mul_ln15_1_fu_436_p2.read()) + sc_biguint<14>(zext_ln18_6_fu_405_p1.read()));
}

void block_mmul_helper::thread_add_ln18_8_fu_508_p2() {
    add_ln18_8_fu_508_p2 = (!mul_ln15_2_fu_502_p2.read().is_01() || !zext_ln18_fu_324_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(mul_ln15_2_fu_502_p2.read()) + sc_biguint<14>(zext_ln18_fu_324_p1.read()));
}

void block_mmul_helper::thread_add_ln18_9_fu_519_p2() {
    add_ln18_9_fu_519_p2 = (!mul_ln15_2_fu_502_p2.read().is_01() || !zext_ln18_2_fu_351_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(mul_ln15_2_fu_502_p2.read()) + sc_biguint<14>(zext_ln18_2_fu_351_p1.read()));
}

void block_mmul_helper::thread_add_ln18_fu_328_p2() {
    add_ln18_fu_328_p2 = (!mul_ln15_fu_318_p2.read().is_01() || !zext_ln18_fu_324_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(mul_ln15_fu_318_p2.read()) + sc_biguint<14>(zext_ln18_fu_324_p1.read()));
}

void block_mmul_helper::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void block_mmul_helper::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void block_mmul_helper::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[10];
}

void block_mmul_helper::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void block_mmul_helper::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void block_mmul_helper::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void block_mmul_helper::thread_ap_CS_fsm_state15() {
    ap_CS_fsm_state15 = ap_CS_fsm.read()[14];
}

void block_mmul_helper::thread_ap_CS_fsm_state16() {
    ap_CS_fsm_state16 = ap_CS_fsm.read()[15];
}

void block_mmul_helper::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read()[16];
}

void block_mmul_helper::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read()[17];
}

void block_mmul_helper::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void block_mmul_helper::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void block_mmul_helper::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void block_mmul_helper::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void block_mmul_helper::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void block_mmul_helper::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void block_mmul_helper::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void block_mmul_helper::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void block_mmul_helper::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void block_mmul_helper::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void block_mmul_helper::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state18.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void block_mmul_helper::thread_grp_fu_294_p3() {
    grp_fu_294_p3 = (!icmp_ln14_reg_1042.read()[0].is_01())? sc_lv<16>(): ((icmp_ln14_reg_1042.read()[0].to_bool())? ap_const_lv16_0: reg_286.read());
}

void block_mmul_helper::thread_grp_fu_301_p3() {
    grp_fu_301_p3 = (!icmp_ln14_reg_1042.read()[0].is_01())? sc_lv<16>(): ((icmp_ln14_reg_1042.read()[0].to_bool())? ap_const_lv16_0: reg_290.read());
}

void block_mmul_helper::thread_icmp_ln10_fu_618_p2() {
    icmp_ln10_fu_618_p2 = (!k_0_reg_263.read().is_01() || !ap_const_lv7_64.is_01())? sc_lv<1>(): sc_lv<1>(k_0_reg_263.read() == ap_const_lv7_64);
}

void block_mmul_helper::thread_icmp_ln14_fu_630_p2() {
    icmp_ln14_fu_630_p2 = (!k_0_reg_263.read().is_01() || !ap_const_lv7_0.is_01())? sc_lv<1>(): sc_lv<1>(k_0_reg_263.read() == ap_const_lv7_0);
}

void block_mmul_helper::thread_icmp_ln15_1_fu_426_p2() {
    icmp_ln15_1_fu_426_p2 = (!add_ln15_fu_420_p2.read().is_01() || !ap_const_lv7_64.is_01())? sc_lv<1>(): (sc_biguint<7>(add_ln15_fu_420_p2.read()) < sc_biguint<7>(ap_const_lv7_64));
}

void block_mmul_helper::thread_icmp_ln15_2_fu_492_p2() {
    icmp_ln15_2_fu_492_p2 = (!add_ln15_1_fu_486_p2.read().is_01() || !ap_const_lv7_64.is_01())? sc_lv<1>(): (sc_biguint<7>(add_ln15_1_fu_486_p2.read()) < sc_biguint<7>(ap_const_lv7_64));
}

void block_mmul_helper::thread_icmp_ln15_3_fu_558_p2() {
    icmp_ln15_3_fu_558_p2 = (!add_ln15_2_fu_552_p2.read().is_01() || !ap_const_lv7_64.is_01())? sc_lv<1>(): (sc_biguint<7>(add_ln15_2_fu_552_p2.read()) < sc_biguint<7>(ap_const_lv7_64));
}

void block_mmul_helper::thread_icmp_ln15_fu_308_p2() {
    icmp_ln15_fu_308_p2 = (!ii.read().is_01() || !ap_const_lv7_64.is_01())? sc_lv<1>(): (sc_biguint<7>(ii.read()) < sc_biguint<7>(ap_const_lv7_64));
}

void block_mmul_helper::thread_icmp_ln16_1_fu_372_p2() {
    icmp_ln16_1_fu_372_p2 = (!add_ln16_1_fu_366_p2.read().is_01() || !ap_const_lv7_64.is_01())? sc_lv<1>(): (sc_biguint<7>(add_ln16_1_fu_366_p2.read()) < sc_biguint<7>(ap_const_lv7_64));
}

void block_mmul_helper::thread_icmp_ln16_2_fu_399_p2() {
    icmp_ln16_2_fu_399_p2 = (!add_ln16_2_fu_393_p2.read().is_01() || !ap_const_lv7_64.is_01())? sc_lv<1>(): (sc_biguint<7>(add_ln16_2_fu_393_p2.read()) < sc_biguint<7>(ap_const_lv7_64));
}

void block_mmul_helper::thread_icmp_ln16_fu_345_p2() {
    icmp_ln16_fu_345_p2 = (!add_ln16_fu_339_p2.read().is_01() || !ap_const_lv7_64.is_01())? sc_lv<1>(): (sc_biguint<7>(add_ln16_fu_339_p2.read()) < sc_biguint<7>(ap_const_lv7_64));
}

void block_mmul_helper::thread_k_fu_624_p2() {
    k_fu_624_p2 = (!k_0_reg_263.read().is_01() || !ap_const_lv7_1.is_01())? sc_lv<7>(): (sc_biguint<7>(k_0_reg_263.read()) + sc_biguint<7>(ap_const_lv7_1));
}

void block_mmul_helper::thread_mul_ln15_1_fu_436_p0() {
    mul_ln15_1_fu_436_p0 =  (sc_lv<7>) (mul_ln15_1_fu_436_p00.read());
}

void block_mmul_helper::thread_mul_ln15_1_fu_436_p00() {
    mul_ln15_1_fu_436_p00 = esl_zext<14,7>(add_ln15_fu_420_p2.read());
}

void block_mmul_helper::thread_mul_ln15_1_fu_436_p2() {
    mul_ln15_1_fu_436_p2 = (!mul_ln15_1_fu_436_p0.read().is_01() || !ap_const_lv14_64.is_01())? sc_lv<14>(): sc_biguint<7>(mul_ln15_1_fu_436_p0.read()) * sc_biguint<14>(ap_const_lv14_64);
}

void block_mmul_helper::thread_mul_ln15_2_fu_502_p0() {
    mul_ln15_2_fu_502_p0 =  (sc_lv<7>) (mul_ln15_2_fu_502_p00.read());
}

void block_mmul_helper::thread_mul_ln15_2_fu_502_p00() {
    mul_ln15_2_fu_502_p00 = esl_zext<14,7>(add_ln15_1_fu_486_p2.read());
}

void block_mmul_helper::thread_mul_ln15_2_fu_502_p2() {
    mul_ln15_2_fu_502_p2 = (!mul_ln15_2_fu_502_p0.read().is_01() || !ap_const_lv14_64.is_01())? sc_lv<14>(): sc_biguint<7>(mul_ln15_2_fu_502_p0.read()) * sc_biguint<14>(ap_const_lv14_64);
}

void block_mmul_helper::thread_mul_ln15_3_fu_568_p0() {
    mul_ln15_3_fu_568_p0 =  (sc_lv<7>) (mul_ln15_3_fu_568_p00.read());
}

void block_mmul_helper::thread_mul_ln15_3_fu_568_p00() {
    mul_ln15_3_fu_568_p00 = esl_zext<14,7>(add_ln15_2_fu_552_p2.read());
}

void block_mmul_helper::thread_mul_ln15_3_fu_568_p2() {
    mul_ln15_3_fu_568_p2 = (!mul_ln15_3_fu_568_p0.read().is_01() || !ap_const_lv14_64.is_01())? sc_lv<14>(): sc_biguint<7>(mul_ln15_3_fu_568_p0.read()) * sc_biguint<14>(ap_const_lv14_64);
}

void block_mmul_helper::thread_mul_ln15_fu_318_p0() {
    mul_ln15_fu_318_p0 =  (sc_lv<7>) (mul_ln15_fu_318_p00.read());
}

void block_mmul_helper::thread_mul_ln15_fu_318_p00() {
    mul_ln15_fu_318_p00 = esl_zext<14,7>(ii.read());
}

void block_mmul_helper::thread_mul_ln15_fu_318_p2() {
    mul_ln15_fu_318_p2 = (!mul_ln15_fu_318_p0.read().is_01() || !ap_const_lv14_64.is_01())? sc_lv<14>(): sc_biguint<7>(mul_ln15_fu_318_p0.read()) * sc_biguint<14>(ap_const_lv14_64);
}

void block_mmul_helper::thread_out_r_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()))) {
        out_r_address0 = out_addr_14_reg_1024.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        out_r_address0 = out_addr_12_reg_1014.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()))) {
        out_r_address0 = out_addr_10_reg_994.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()))) {
        out_r_address0 = out_addr_8_reg_984.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        out_r_address0 = out_addr_6_reg_964.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        out_r_address0 = out_addr_4_reg_954.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()))) {
        out_r_address0 = out_addr_2_reg_924.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        out_r_address0 = out_addr_reg_894.read();
    } else {
        out_r_address0 = "XXXXXXXXXXXXXX";
    }
}

void block_mmul_helper::thread_out_r_address1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()))) {
        out_r_address1 = out_addr_15_reg_1029.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        out_r_address1 = out_addr_13_reg_1019.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()))) {
        out_r_address1 = out_addr_11_reg_999.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()))) {
        out_r_address1 = out_addr_9_reg_989.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()))) {
        out_r_address1 = out_addr_7_reg_969.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        out_r_address1 = out_addr_5_reg_959.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()))) {
        out_r_address1 = out_addr_3_reg_939.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()))) {
        out_r_address1 = out_addr_1_reg_909.read();
    } else {
        out_r_address1 = "XXXXXXXXXXXXXX";
    }
}

void block_mmul_helper::thread_out_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        out_r_ce0 = ap_const_logic_1;
    } else {
        out_r_ce0 = ap_const_logic_0;
    }
}

void block_mmul_helper::thread_out_r_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        out_r_ce1 = ap_const_logic_1;
    } else {
        out_r_ce1 = ap_const_logic_0;
    }
}

void block_mmul_helper::thread_out_r_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        out_r_d0 = add_ln17_14_reg_1254.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        out_r_d0 = add_ln17_12_reg_1234.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        out_r_d0 = add_ln17_10_reg_1224.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        out_r_d0 = add_ln17_8_reg_1214.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        out_r_d0 = add_ln17_6_reg_1204.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        out_r_d0 = add_ln17_4_reg_1194.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        out_r_d0 = add_ln17_2_reg_1184.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        out_r_d0 = add_ln17_reg_1142.read();
    } else {
        out_r_d0 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void block_mmul_helper::thread_out_r_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read())) {
        out_r_d1 = add_ln17_15_reg_1259.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read())) {
        out_r_d1 = add_ln17_13_reg_1239.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read())) {
        out_r_d1 = add_ln17_11_reg_1229.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        out_r_d1 = add_ln17_9_reg_1219.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        out_r_d1 = add_ln17_7_reg_1209.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        out_r_d1 = add_ln17_5_reg_1199.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read())) {
        out_r_d1 = add_ln17_3_reg_1189.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        out_r_d1 = add_ln17_1_reg_1147.read();
    } else {
        out_r_d1 =  (sc_lv<16>) ("XXXXXXXXXXXXXXXX");
    }
}

void block_mmul_helper::thread_out_r_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        out_r_we0 = ap_const_logic_1;
    } else {
        out_r_we0 = ap_const_logic_0;
    }
}

void block_mmul_helper::thread_out_r_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state17.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state15.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state16.read()))) {
        out_r_we1 = ap_const_logic_1;
    } else {
        out_r_we1 = ap_const_logic_0;
    }
}

void block_mmul_helper::thread_select_ln14_14_fu_765_p3() {
    select_ln14_14_fu_765_p3 = (!icmp_ln14_reg_1042.read()[0].is_01())? sc_lv<16>(): ((icmp_ln14_reg_1042.read()[0].to_bool())? ap_const_lv16_0: out_r_q0.read());
}

void block_mmul_helper::thread_select_ln14_15_fu_772_p3() {
    select_ln14_15_fu_772_p3 = (!icmp_ln14_reg_1042.read()[0].is_01())? sc_lv<16>(): ((icmp_ln14_reg_1042.read()[0].to_bool())? ap_const_lv16_0: out_r_q1.read());
}

void block_mmul_helper::thread_select_ln15_1_fu_730_p3() {
    select_ln15_1_fu_730_p3 = (!icmp_ln15_1_reg_944.read()[0].is_01())? sc_lv<16>(): ((icmp_ln15_1_reg_944.read()[0].to_bool())? A_q1.read(): ap_const_lv16_0);
}

void block_mmul_helper::thread_select_ln15_2_fu_751_p3() {
    select_ln15_2_fu_751_p3 = (!icmp_ln15_2_reg_974.read()[0].is_01())? sc_lv<16>(): ((icmp_ln15_2_reg_974.read()[0].to_bool())? A_q0.read(): ap_const_lv16_0);
}

void block_mmul_helper::thread_select_ln15_3_fu_758_p3() {
    select_ln15_3_fu_758_p3 = (!icmp_ln15_3_reg_1004.read()[0].is_01())? sc_lv<16>(): ((icmp_ln15_3_reg_1004.read()[0].to_bool())? A_q1.read(): ap_const_lv16_0);
}

void block_mmul_helper::thread_select_ln15_fu_716_p3() {
    select_ln15_fu_716_p3 = (!icmp_ln15_reg_879.read()[0].is_01())? sc_lv<16>(): ((icmp_ln15_reg_879.read()[0].to_bool())? A_q0.read(): ap_const_lv16_0);
}

void block_mmul_helper::thread_select_ln16_1_fu_737_p3() {
    select_ln16_1_fu_737_p3 = (!icmp_ln16_1_reg_914.read()[0].is_01())? sc_lv<16>(): ((icmp_ln16_1_reg_914.read()[0].to_bool())? B_q0.read(): ap_const_lv16_0);
}

void block_mmul_helper::thread_select_ln16_2_fu_744_p3() {
    select_ln16_2_fu_744_p3 = (!icmp_ln16_2_reg_929.read()[0].is_01())? sc_lv<16>(): ((icmp_ln16_2_reg_929.read()[0].to_bool())? B_q1.read(): ap_const_lv16_0);
}

void block_mmul_helper::thread_select_ln16_fu_723_p3() {
    select_ln16_fu_723_p3 = (!icmp_ln16_reg_899.read()[0].is_01())? sc_lv<16>(): ((icmp_ln16_reg_899.read()[0].to_bool())? B_q1.read(): ap_const_lv16_0);
}

void block_mmul_helper::thread_zext_ln15_4_fu_636_p1() {
    zext_ln15_4_fu_636_p1 = esl_zext<14,7>(k_0_reg_263.read());
}

void block_mmul_helper::thread_zext_ln15_5_fu_645_p1() {
    zext_ln15_5_fu_645_p1 = esl_zext<64,14>(add_ln15_3_fu_640_p2.read());
}

void block_mmul_helper::thread_zext_ln15_6_fu_655_p1() {
    zext_ln15_6_fu_655_p1 = esl_zext<64,14>(add_ln15_4_fu_650_p2.read());
}

void block_mmul_helper::thread_zext_ln15_7_fu_700_p1() {
    zext_ln15_7_fu_700_p1 = esl_zext<64,14>(add_ln15_5_reg_1060.read());
}

void block_mmul_helper::thread_zext_ln15_8_fu_704_p1() {
    zext_ln15_8_fu_704_p1 = esl_zext<64,14>(add_ln15_6_reg_1065.read());
}

void block_mmul_helper::thread_zext_ln16_1_fu_685_p1() {
    zext_ln16_1_fu_685_p1 = esl_zext<64,14>(add_ln16_4_fu_680_p2.read());
}

void block_mmul_helper::thread_zext_ln16_2_fu_708_p1() {
    zext_ln16_2_fu_708_p1 = esl_zext<64,14>(add_ln16_5_reg_1080.read());
}

void block_mmul_helper::thread_zext_ln16_3_fu_712_p1() {
    zext_ln16_3_fu_712_p1 = esl_zext<64,14>(add_ln16_6_reg_1085.read());
}

void block_mmul_helper::thread_zext_ln16_fu_675_p1() {
    zext_ln16_fu_675_p1 = esl_zext<64,14>(add_ln16_3_fu_670_p2.read());
}

void block_mmul_helper::thread_zext_ln18_10_fu_470_p1() {
    zext_ln18_10_fu_470_p1 = esl_zext<64,14>(add_ln18_6_fu_464_p2.read());
}

void block_mmul_helper::thread_zext_ln18_11_fu_481_p1() {
    zext_ln18_11_fu_481_p1 = esl_zext<64,14>(add_ln18_7_fu_475_p2.read());
}

void block_mmul_helper::thread_zext_ln18_12_fu_514_p1() {
    zext_ln18_12_fu_514_p1 = esl_zext<64,14>(add_ln18_8_fu_508_p2.read());
}

void block_mmul_helper::thread_zext_ln18_13_fu_525_p1() {
    zext_ln18_13_fu_525_p1 = esl_zext<64,14>(add_ln18_9_fu_519_p2.read());
}

void block_mmul_helper::thread_zext_ln18_14_fu_536_p1() {
    zext_ln18_14_fu_536_p1 = esl_zext<64,14>(add_ln18_10_fu_530_p2.read());
}

void block_mmul_helper::thread_zext_ln18_15_fu_547_p1() {
    zext_ln18_15_fu_547_p1 = esl_zext<64,14>(add_ln18_11_fu_541_p2.read());
}

void block_mmul_helper::thread_zext_ln18_16_fu_580_p1() {
    zext_ln18_16_fu_580_p1 = esl_zext<64,14>(add_ln18_12_fu_574_p2.read());
}

void block_mmul_helper::thread_zext_ln18_17_fu_591_p1() {
    zext_ln18_17_fu_591_p1 = esl_zext<64,14>(add_ln18_13_fu_585_p2.read());
}

void block_mmul_helper::thread_zext_ln18_18_fu_602_p1() {
    zext_ln18_18_fu_602_p1 = esl_zext<64,14>(add_ln18_14_fu_596_p2.read());
}

void block_mmul_helper::thread_zext_ln18_19_fu_613_p1() {
    zext_ln18_19_fu_613_p1 = esl_zext<64,14>(add_ln18_15_fu_607_p2.read());
}

void block_mmul_helper::thread_zext_ln18_1_fu_334_p1() {
    zext_ln18_1_fu_334_p1 = esl_zext<64,14>(add_ln18_fu_328_p2.read());
}

void block_mmul_helper::thread_zext_ln18_2_fu_351_p1() {
    zext_ln18_2_fu_351_p1 = esl_zext<14,7>(add_ln16_fu_339_p2.read());
}

void block_mmul_helper::thread_zext_ln18_3_fu_361_p1() {
    zext_ln18_3_fu_361_p1 = esl_zext<64,14>(add_ln18_1_fu_355_p2.read());
}

void block_mmul_helper::thread_zext_ln18_4_fu_378_p1() {
    zext_ln18_4_fu_378_p1 = esl_zext<14,7>(add_ln16_1_fu_366_p2.read());
}

void block_mmul_helper::thread_zext_ln18_5_fu_388_p1() {
    zext_ln18_5_fu_388_p1 = esl_zext<64,14>(add_ln18_2_fu_382_p2.read());
}

void block_mmul_helper::thread_zext_ln18_6_fu_405_p1() {
    zext_ln18_6_fu_405_p1 = esl_zext<14,7>(add_ln16_2_fu_393_p2.read());
}

void block_mmul_helper::thread_zext_ln18_7_fu_415_p1() {
    zext_ln18_7_fu_415_p1 = esl_zext<64,14>(add_ln18_3_fu_409_p2.read());
}

void block_mmul_helper::thread_zext_ln18_8_fu_448_p1() {
    zext_ln18_8_fu_448_p1 = esl_zext<64,14>(add_ln18_4_fu_442_p2.read());
}

void block_mmul_helper::thread_zext_ln18_9_fu_459_p1() {
    zext_ln18_9_fu_459_p1 = esl_zext<64,14>(add_ln18_5_fu_453_p2.read());
}

void block_mmul_helper::thread_zext_ln18_fu_324_p1() {
    zext_ln18_fu_324_p1 = esl_zext<14,7>(jj.read());
}

void block_mmul_helper::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln10_fu_618_p2.read()))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state18;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<18>) ("XXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

